"use client";

import { getCompany } from "@/lib/settings";

export type ReportMetric = { label: string; value: string; tone?: "green" | "blue" | "amber" | "red" | "neutral" };
export type ReportTable = { title?: string; headers: string[]; rows: Array<string[]>; totals?: string[]; note?: string };
type Props = { locale: string; title: string; subtitle: string; period: string; orientation?: "portrait" | "landscape"; metrics?: ReportMetric[]; tables: ReportTable[]; reportCode: string };

const esc = (value: unknown) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char] || char));

export default function StructuredReportPrintButton({ locale, title, subtitle, period, orientation = "portrait", metrics = [], tables, reportCode }: Props) {
  const ar = locale === "ar";
  const onPrint = async () => {
    const win = window.open("", "_blank");
    if (!win) return;
    let company: any = null;
    try { company = (await getCompany()).data; } catch {}
    const name = company?.name || company?.name_ar || "SMACC";
    const logo = company?.logo_data ? `<img src="${esc(company.logo_data)}" alt="logo">` : "";
    const detail = [company?.vat_number ? `${ar ? "الرقم الضريبي" : "VAT"}: ${company.vat_number}` : "", company?.cr_number ? `${ar ? "السجل التجاري" : "CR"}: ${company.cr_number}` : "", company?.address_city || ""].filter(Boolean).join(" · ");
    const metricsHtml = metrics.length ? `<section class="metrics">${metrics.map(m => `<div class="metric ${m.tone || "neutral"}"><span>${esc(m.label)}</span><b dir="ltr">${esc(m.value)}</b></div>`).join("")}</section>` : "";
    const tablesHtml = tables.map(table => `<section class="block">${table.title ? `<h2>${esc(table.title)}</h2>` : ""}<table><thead><tr>${table.headers.map(head => `<th>${esc(head)}</th>`).join("")}</tr></thead><tbody>${table.rows.length ? table.rows.map(row => `<tr>${row.map((cell, i) => `<td class="${i ? "number" : "label"}">${esc(cell)}</td>`).join("")}</tr>`).join("") : `<tr><td colspan="${table.headers.length}" class="empty">${ar ? "لا توجد بيانات ضمن الفترة المختارة" : "No data for the selected period"}</td></tr>`}</tbody>${table.totals ? `<tfoot><tr>${table.totals.map((cell, i) => `<td class="${i ? "number" : "label"}">${esc(cell)}</td>`).join("")}</tr></tfoot>` : ""}</table>${table.note ? `<p class="note">${esc(table.note)}</p>` : ""}</section>`).join("");
    const generated = new Date().toLocaleString(ar ? "ar-SA" : "en-GB");
    win.document.write(`<!doctype html><html dir="${ar ? "rtl" : "ltr"}"><head><meta charset="utf-8"><title>${esc(title)}</title><style>
      @page{size:A4 ${orientation};margin:10mm}*{box-sizing:border-box}body{margin:0;background:#fff;color:#17342D;font-family:"IBM Plex Sans Arabic",Cairo,Arial,sans-serif;font-size:10px;-webkit-print-color-adjust:exact;print-color-adjust:exact}.sheet{min-height:${orientation === "landscape" ? "190" : "277"}mm;position:relative;padding-bottom:19mm}.head{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:start;border-bottom:2px solid #3E0865;padding-bottom:8px}.company{display:flex;gap:8px}.company img{width:45px;height:45px;object-fit:contain;border:1px solid #C8D0C7;padding:2px}.company strong{display:block;color:#3E0865;font-size:13px}.company small{display:block;color:#5C6D63;font-size:8px;margin-top:4px}.title{text-align:center}.title h1{margin:0;color:#3E0865;font-size:17px}.title p{margin:4px 0 0;color:#5C6D63;font-size:9px}.meta{text-align:end;font-size:8px;color:#5C6D63;line-height:1.7}.meta b{color:#17342D}.period{margin:10px 0 8px;padding:6px 8px;background:#F1F6F2;border:1px solid #C8D0C7;color:#24453B;font-weight:700}.period b{font-family:"Courier New",monospace;margin-inline-start:6px}.metrics{display:grid;grid-template-columns:repeat(${Math.min(Math.max(metrics.length, 1), 4)},1fr);gap:6px;margin:0 0 10px}.metric{border:1px solid #C8D0C7;padding:6px 7px;background:#fff}.metric span{display:block;color:#617168;font-size:8px}.metric b{display:block;margin-top:3px;font:700 12px "Courier New",monospace}.metric.green b{color:#087443}.metric.blue b{color:#3E0865}.metric.amber b{color:#B45309}.metric.red b{color:#B42318}.block{margin-top:9px;break-inside:avoid}.block h2{margin:0;padding:6px 8px;background:#E6EEE6;border:1px solid #BFCAC0;border-bottom:0;color:#24453B;font-size:10px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #BFCAC0;padding:5px 4px}th{background:#F0F4EF;color:#24453B;text-align:center;font-weight:800}td.label{text-align:start;font-family:"IBM Plex Sans Arabic",Cairo,Arial,sans-serif}td.number{text-align:end;font-family:"Courier New",monospace;direction:ltr;white-space:nowrap}tfoot td{background:#EEF3ED;font-weight:800;border-top:2px solid #3E0865}.empty{text-align:center;color:#697970;padding:12px!important}.note{margin:0;border:1px solid #C8D0C7;border-top:0;padding:5px 7px;color:#617168;font-size:8px}.foot{position:absolute;bottom:0;inset-inline:0;display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:12px;border-top:1px solid #C8D0C7;padding-top:7px;text-align:center;color:#617168;font-size:8px}.sign{height:22px;border-bottom:1px dotted #9BA99F}.sign b{display:block;color:#24453B;margin-bottom:11px}@media print{thead{display:table-header-group}tfoot{display:table-footer-group}tr{break-inside:avoid}}
    </style></head><body><main class="sheet"><header class="head"><section class="company">${logo}<div><strong>${esc(name)}</strong><small>${esc(detail)}</small></div></section><section class="title"><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></section><section class="meta"><div><b>${ar ? "رمز التقرير:" : "Report code:"}</b> ${esc(reportCode)}</div><div><b>${ar ? "تاريخ الطباعة:" : "Printed:"}</b> ${esc(generated)}</div></section></header><div class="period">${ar ? "فترة التقرير:" : "Report period:"}<b>${esc(period)}</b></div>${metricsHtml}${tablesHtml}<footer class="foot"><div class="sign"><b>${ar ? "إعداد: المحاسب" : "Prepared by: Accountant"}</b></div><div class="sign"><b>${ar ? "مراجعة: المدير المالي" : "Reviewed by: Finance Manager"}</b></div><div class="sign"><b>${ar ? "اعتماد: الإدارة" : "Approved by: Management"}</b></div><div class="sign"><b>${ar ? "صفحة 1" : "Page 1"}</b></div></footer></main><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);
    win.document.close();
  };
  return <button type="button" className="btn btn-secondary btn-sm" onClick={onPrint}>🖨️ {ar ? "طباعة تقرير" : "Print report"}</button>;
}
