"""قالب شجرة الحسابات ومفاتيح الربط التشغيلية الافتراضية.

هذا الملف لا ينفذ قيودًا ولا يكتب في قاعدة البيانات. تستخدمه خدمة المحاسبة
لإنشاء القالب مرة واحدة فقط للشركات التي لا تملك حسابات مسبقًا.
"""
from app.models.accounting import AccountNature, AccountType


# code, الاسم العربي، الاسم الإنجليزي، النوع، طبيعة الرصيد، رمز الأب، هل يقبل القيد، هل يسمح بقيد يدوي
DEFAULT_CHART: list[tuple[str, str, str, AccountType, AccountNature, str | None, bool, bool]] = [
    ("1000", "الأصول", "Assets", AccountType.ASSET, AccountNature.DEBIT, None, False, False),
    ("1100", "الأصول المتداولة", "Current Assets", AccountType.ASSET, AccountNature.DEBIT, "1000", False, False),
    ("1110", "الصندوق", "Cash on Hand", AccountType.ASSET, AccountNature.DEBIT, "1100", False, False),
    ("1111", "الصندوق الرئيسي", "Main Cash", AccountType.ASSET, AccountNature.DEBIT, "1110", True, True),
    ("1120", "البنوك", "Banks", AccountType.ASSET, AccountNature.DEBIT, "1100", False, False),
    ("1121", "البنك الرئيسي", "Main Bank", AccountType.ASSET, AccountNature.DEBIT, "1120", True, True),
    ("1130", "وسائل الدفع الإلكترونية", "Electronic Payments", AccountType.ASSET, AccountNature.DEBIT, "1100", False, False),
    ("1131", "مدى وشبكة", "Mada and Card Settlements", AccountType.ASSET, AccountNature.DEBIT, "1130", True, True),
    ("1132", "المحافظ الرقمية", "Digital Wallets", AccountType.ASSET, AccountNature.DEBIT, "1130", True, True),
    ("1140", "العملاء والذمم المدينة", "Accounts Receivable", AccountType.ASSET, AccountNature.DEBIT, "1100", False, False),
    ("1141", "ذمم العملاء - عام", "General Accounts Receivable", AccountType.ASSET, AccountNature.DEBIT, "1140", True, True),
    ("1150", "المخزون", "Inventory", AccountType.ASSET, AccountNature.DEBIT, "1100", False, False),
    ("1151", "مخزون بضائع للتجارة", "Merchandise Inventory", AccountType.ASSET, AccountNature.DEBIT, "1150", True, True),
    ("1160", "ضريبة القيمة المضافة المدخلة", "Input VAT", AccountType.ASSET, AccountNature.DEBIT, "1100", False, False),
    ("1161", "ضريبة القيمة المضافة القابلة للاسترداد", "Recoverable Input VAT", AccountType.ASSET, AccountNature.DEBIT, "1160", True, True),
    ("1170", "سلف وعهد الموظفين والمندوبين", "Employee and Rep Advances", AccountType.ASSET, AccountNature.DEBIT, "1100", False, False),
    ("1171", "عهد وسلف الموظفين", "Employee Advances", AccountType.ASSET, AccountNature.DEBIT, "1170", True, True),
    ("1172", "عهد تحصيل المناديب", "Rep Collections in Transit", AccountType.ASSET, AccountNature.DEBIT, "1170", True, True),
    ("1180", "مصروفات مقدمة", "Prepaid Expenses", AccountType.ASSET, AccountNature.DEBIT, "1100", True, True),
    ("1200", "الأصول غير المتداولة", "Non-current Assets", AccountType.ASSET, AccountNature.DEBIT, "1000", False, False),
    ("1210", "الأصول الثابتة", "Fixed Assets", AccountType.ASSET, AccountNature.DEBIT, "1200", False, False),
    ("1211", "أثاث وتجهيزات", "Furniture and Fixtures", AccountType.ASSET, AccountNature.DEBIT, "1210", True, True),
    ("1212", "أجهزة وحواسيب", "Computers and Equipment", AccountType.ASSET, AccountNature.DEBIT, "1210", True, True),
    ("1213", "مركبات", "Vehicles", AccountType.ASSET, AccountNature.DEBIT, "1210", True, True),
    ("1220", "مجمع الإهلاك", "Accumulated Depreciation", AccountType.ASSET, AccountNature.CREDIT, "1200", False, False),
    ("1221", "مجمع إهلاك الأصول", "Accumulated Depreciation - Assets", AccountType.ASSET, AccountNature.CREDIT, "1220", True, False),
    ("2000", "الالتزامات", "Liabilities", AccountType.LIABILITY, AccountNature.CREDIT, None, False, False),
    ("2100", "الالتزامات المتداولة", "Current Liabilities", AccountType.LIABILITY, AccountNature.CREDIT, "2000", False, False),
    ("2110", "الموردون والذمم الدائنة", "Accounts Payable", AccountType.LIABILITY, AccountNature.CREDIT, "2100", False, False),
    ("2111", "ذمم الموردين - عام", "General Accounts Payable", AccountType.LIABILITY, AccountNature.CREDIT, "2110", True, True),
    ("2120", "ضريبة القيمة المضافة المخرجة", "Output VAT", AccountType.LIABILITY, AccountNature.CREDIT, "2100", False, False),
    ("2121", "ضريبة القيمة المضافة المستحقة", "VAT Payable", AccountType.LIABILITY, AccountNature.CREDIT, "2120", True, True),
    ("2130", "رواتب وأجور مستحقة", "Payroll Payable", AccountType.LIABILITY, AccountNature.CREDIT, "2100", True, True),
    ("2140", "مصروفات مستحقة", "Accrued Expenses", AccountType.LIABILITY, AccountNature.CREDIT, "2100", True, True),
    ("2150", "إيرادات مقدمة", "Deferred Revenue", AccountType.LIABILITY, AccountNature.CREDIT, "2100", True, True),
    ("3000", "حقوق الملكية", "Equity", AccountType.EQUITY, AccountNature.CREDIT, None, False, False),
    ("3100", "رأس المال", "Capital", AccountType.EQUITY, AccountNature.CREDIT, "3000", True, True),
    ("3200", "جاري الشريك / المالك", "Owner Current Account", AccountType.EQUITY, AccountNature.CREDIT, "3000", True, True),
    ("3300", "الأرباح المحتجزة", "Retained Earnings", AccountType.EQUITY, AccountNature.CREDIT, "3000", True, False),
    ("4000", "الإيرادات", "Revenue", AccountType.REVENUE, AccountNature.CREDIT, None, False, False),
    ("4100", "إيرادات المبيعات", "Sales Revenue", AccountType.REVENUE, AccountNature.CREDIT, "4000", False, False),
    ("4110", "مبيعات البضائع", "Goods Sales", AccountType.REVENUE, AccountNature.CREDIT, "4100", True, True),
    ("4120", "إيرادات الخدمات", "Service Revenue", AccountType.REVENUE, AccountNature.CREDIT, "4100", True, True),
    ("4190", "خصم مسموح به على المبيعات", "Sales Discounts", AccountType.REVENUE, AccountNature.DEBIT, "4100", True, True),
    ("4200", "إيرادات أخرى", "Other Income", AccountType.REVENUE, AccountNature.CREDIT, "4000", False, False),
    ("4210", "إيرادات أخرى", "Other Income", AccountType.REVENUE, AccountNature.CREDIT, "4200", True, True),
    ("5000", "تكلفة المبيعات", "Cost of Sales", AccountType.EXPENSE, AccountNature.DEBIT, None, False, False),
    ("5100", "تكلفة البضاعة المباعة", "Cost of Goods Sold", AccountType.EXPENSE, AccountNature.DEBIT, "5000", True, False),
    ("5200", "تكلفة خدمات مقدمة", "Cost of Services", AccountType.EXPENSE, AccountNature.DEBIT, "5000", True, True),
    ("6000", "المصروفات التشغيلية", "Operating Expenses", AccountType.EXPENSE, AccountNature.DEBIT, None, False, False),
    ("6110", "رواتب وأجور", "Salaries and Wages", AccountType.EXPENSE, AccountNature.DEBIT, "6000", True, True),
    ("6120", "إيجارات", "Rent Expense", AccountType.EXPENSE, AccountNature.DEBIT, "6000", True, True),
    ("6130", "كهرباء ومياه واتصالات", "Utilities and Communications", AccountType.EXPENSE, AccountNature.DEBIT, "6000", True, True),
    ("6140", "تسويق وإعلان", "Marketing and Advertising", AccountType.EXPENSE, AccountNature.DEBIT, "6000", True, True),
    ("6150", "نقل وشحن", "Transport and Shipping", AccountType.EXPENSE, AccountNature.DEBIT, "6000", True, True),
    ("6160", "صيانة وإصلاح", "Maintenance and Repairs", AccountType.EXPENSE, AccountNature.DEBIT, "6000", True, True),
    ("6170", "عمولات ومكافآت مناديب", "Sales Commissions", AccountType.EXPENSE, AccountNature.DEBIT, "6000", True, True),
    ("6180", "رسوم بنكية وبوابات دفع", "Bank and Payment Gateway Fees", AccountType.EXPENSE, AccountNature.DEBIT, "6000", True, True),
    ("6190", "مصروفات تشغيلية متنوعة", "Miscellaneous Operating Expenses", AccountType.EXPENSE, AccountNature.DEBIT, "6000", True, True),
    ("6200", "الإهلاك", "Depreciation", AccountType.EXPENSE, AccountNature.DEBIT, "6000", False, False),
    ("6210", "مصروف إهلاك", "Depreciation Expense", AccountType.EXPENSE, AccountNature.DEBIT, "6200", True, False),
]


# مفتاح الربط داخل النظام: رمز الحساب الافتراضي في قالب الشجرة.
DEFAULT_MAPPING_CODES: dict[str, str] = {
    "default_cash": "1111",
    "default_bank": "1121",
    "default_card": "1131",
    "default_wallet": "1132",
    "default_ar": "1141",
    "inventory": "1151",
    "vat_input": "1161",
    "employee_advances": "1171",
    "rep_collections": "1172",
    "default_ap": "2111",
    "vat_output": "2121",
    "payroll_payable": "2130",
    "accrued_expenses": "2140",
    "capital": "3100",
    "sales_goods": "4110",
    "sales_services": "4120",
    "sales_discounts": "4190",
    "other_income": "4210",
    "cogs_goods": "5100",
    "cost_services": "5200",
    "payroll_expense": "6110",
    "operating_expenses": "6190",
    "inventory_adjustment_gain": "4210",
    "inventory_adjustment_loss": "6190",
}

REQUIRED_MAPPING_KEYS: tuple[str, ...] = (
    "default_cash", "default_ar", "inventory", "vat_input", "default_ap",
    "vat_output", "sales_goods", "cogs_goods",
)
