"""قالب شجرة الحسابات الافتراضي ومفاتيح الربط التشغيلية.

لا ينفذ هذا الملف قيودًا ولا يكتب في قاعدة البيانات. تستخدمه خدمة المحاسبة
مرة واحدة فقط للشركات التي لا تمتلك أي حسابات سابقة. جميع الأكواد هنا من
الشجرة المعتمدة ذات الست خانات، والحسابات التجميعية لا تقبل قيدًا مباشرًا.
"""
from app.models.accounting import AccountNature, AccountType


# code, الاسم العربي، الاسم الإنجليزي، النوع، طبيعة الرصيد، رمز الأب، هل يقبل القيد، هل يسمح بقيد يدوي
DEFAULT_CHART: list[tuple[str, str, str, AccountType, AccountNature, str | None, bool, bool]] = [
    # 100000 الأصول
    ("100000", "الأصول", "Assets", AccountType.ASSET, AccountNature.DEBIT, None, False, False),
    ("110000", "الأصول المتداولة", "Current Assets", AccountType.ASSET, AccountNature.DEBIT, "100000", False, False),
    ("111000", "النقدية", "Cash", AccountType.ASSET, AccountNature.DEBIT, "110000", False, False),
    ("111001", "الصندوق الرئيسي", "Main Cash", AccountType.ASSET, AccountNature.DEBIT, "111000", True, True),
    ("111002", "صندوق الفرع", "Branch Cash", AccountType.ASSET, AccountNature.DEBIT, "111000", True, True),
    ("111003", "عهد نقدية", "Cash Advances", AccountType.ASSET, AccountNature.DEBIT, "111000", True, True),
    ("112000", "البنوك", "Banks", AccountType.ASSET, AccountNature.DEBIT, "110000", False, False),
    ("112001", "البنك - الحساب الجاري", "Bank - Current Account", AccountType.ASSET, AccountNature.DEBIT, "112000", True, True),
    ("112002", "البنك - حساب التوفير", "Bank - Savings Account", AccountType.ASSET, AccountNature.DEBIT, "112000", True, True),
    ("112003", "بنك الراجحي", "Al Rajhi Bank", AccountType.ASSET, AccountNature.DEBIT, "112000", True, True),
    ("112004", "البنك الأهلي", "Saudi National Bank", AccountType.ASSET, AccountNature.DEBIT, "112000", True, True),
    ("112005", "بنك الرياض", "Riyad Bank", AccountType.ASSET, AccountNature.DEBIT, "112000", True, True),
    ("113000", "العملاء والذمم المدينة", "Customers and Receivables", AccountType.ASSET, AccountNature.DEBIT, "110000", False, False),
    ("113001", "العملاء", "Customers", AccountType.ASSET, AccountNature.DEBIT, "113000", True, True),
    ("113002", "عملاء آجلة", "Credit Customers", AccountType.ASSET, AccountNature.DEBIT, "113000", True, True),
    ("113003", "شيكات تحت التحصيل", "Checks Under Collection", AccountType.ASSET, AccountNature.DEBIT, "113000", True, True),
    ("113004", "مخصص الديون المشكوك فيها", "Allowance for Doubtful Debts", AccountType.ASSET, AccountNature.CREDIT, "113000", True, False),
    ("114000", "المخزون", "Inventory", AccountType.ASSET, AccountNature.DEBIT, "110000", False, False),
    ("114001", "مخزون البضائع", "Merchandise Inventory", AccountType.ASSET, AccountNature.DEBIT, "114000", True, True),
    ("114002", "مخزون الأجهزة", "Device Inventory", AccountType.ASSET, AccountNature.DEBIT, "114000", True, True),
    ("114003", "مخزون قطع الغيار", "Spare Parts Inventory", AccountType.ASSET, AccountNature.DEBIT, "114000", True, True),
    ("114004", "مخزون الإكسسوارات", "Accessories Inventory", AccountType.ASSET, AccountNature.DEBIT, "114000", True, True),
    ("114005", "بضاعة بالطريق", "Goods in Transit", AccountType.ASSET, AccountNature.DEBIT, "114000", True, True),
    ("114006", "مخزون تالف", "Damaged Inventory", AccountType.ASSET, AccountNature.DEBIT, "114000", True, False),
    ("115000", "الضرائب والذمم الحكومية", "Taxes and Government Receivables", AccountType.ASSET, AccountNature.DEBIT, "110000", False, False),
    ("115001", "ضريبة القيمة المضافة - مدخلات", "Input VAT", AccountType.ASSET, AccountNature.DEBIT, "115000", True, True),
    ("115002", "ضريبة مدخلات قابلة للاسترداد", "Recoverable Input VAT", AccountType.ASSET, AccountNature.DEBIT, "115000", True, True),
    ("115003", "أرصدة حكومية مدينة", "Government Receivables", AccountType.ASSET, AccountNature.DEBIT, "115000", True, True),
    ("116000", "المصروفات المدفوعة مقدماً", "Prepaid Expenses", AccountType.ASSET, AccountNature.DEBIT, "110000", False, False),
    ("116001", "إيجار مدفوع مقدماً", "Prepaid Rent", AccountType.ASSET, AccountNature.DEBIT, "116000", True, True),
    ("116002", "تأمين مدفوع مقدماً", "Prepaid Insurance", AccountType.ASSET, AccountNature.DEBIT, "116000", True, True),
    ("116003", "اشتراكات مدفوعة مقدماً", "Prepaid Subscriptions", AccountType.ASSET, AccountNature.DEBIT, "116000", True, True),
    ("117000", "أصول متداولة أخرى", "Other Current Assets", AccountType.ASSET, AccountNature.DEBIT, "110000", False, False),
    ("117001", "سلف الموظفين", "Employee Advances", AccountType.ASSET, AccountNature.DEBIT, "117000", True, True),
    ("117002", "عهد الموظفين", "Employee Custody", AccountType.ASSET, AccountNature.DEBIT, "117000", True, True),
    ("117003", "تأمينات لدى الغير", "Deposits with Others", AccountType.ASSET, AccountNature.DEBIT, "117000", True, True),
    ("120000", "الأصول غير المتداولة", "Non-current Assets", AccountType.ASSET, AccountNature.DEBIT, "100000", False, False),
    ("121000", "الممتلكات والمباني", "Property and Buildings", AccountType.ASSET, AccountNature.DEBIT, "120000", False, False),
    ("121001", "الأراضي", "Land", AccountType.ASSET, AccountNature.DEBIT, "121000", True, True),
    ("121002", "المباني", "Buildings", AccountType.ASSET, AccountNature.DEBIT, "121000", True, True),
    ("121003", "تحسينات المباني", "Building Improvements", AccountType.ASSET, AccountNature.DEBIT, "121000", True, True),
    ("122000", "الأثاث والتجهيزات", "Furniture and Fixtures", AccountType.ASSET, AccountNature.DEBIT, "120000", False, False),
    ("122001", "الأثاث", "Furniture", AccountType.ASSET, AccountNature.DEBIT, "122000", True, True),
    ("122002", "تجهيزات المعارض", "Showroom Fixtures", AccountType.ASSET, AccountNature.DEBIT, "122000", True, True),
    ("122003", "ديكورات", "Decorations", AccountType.ASSET, AccountNature.DEBIT, "122000", True, True),
    ("123000", "المركبات", "Vehicles", AccountType.ASSET, AccountNature.DEBIT, "120000", False, False),
    ("123001", "سيارات", "Cars", AccountType.ASSET, AccountNature.DEBIT, "123000", True, True),
    ("123002", "مركبات نقل", "Transport Vehicles", AccountType.ASSET, AccountNature.DEBIT, "123000", True, True),
    ("123003", "دراجات", "Motorcycles", AccountType.ASSET, AccountNature.DEBIT, "123000", True, True),
    ("124000", "الأجهزة والمعدات", "Equipment", AccountType.ASSET, AccountNature.DEBIT, "120000", False, False),
    ("124001", "أجهزة كمبيوتر", "Computers", AccountType.ASSET, AccountNature.DEBIT, "124000", True, True),
    ("124002", "معدات", "Equipment", AccountType.ASSET, AccountNature.DEBIT, "124000", True, True),
    ("124003", "أجهزة مكتبية", "Office Equipment", AccountType.ASSET, AccountNature.DEBIT, "124000", True, True),
    ("125000", "مجمع الاستهلاك", "Accumulated Depreciation", AccountType.ASSET, AccountNature.CREDIT, "120000", False, False),
    ("125001", "مجمع استهلاك المباني", "Accumulated Depreciation - Buildings", AccountType.ASSET, AccountNature.CREDIT, "125000", True, False),
    ("125002", "مجمع استهلاك الأثاث", "Accumulated Depreciation - Furniture", AccountType.ASSET, AccountNature.CREDIT, "125000", True, False),
    ("125003", "مجمع استهلاك المركبات", "Accumulated Depreciation - Vehicles", AccountType.ASSET, AccountNature.CREDIT, "125000", True, False),
    ("125004", "مجمع استهلاك الأجهزة", "Accumulated Depreciation - Equipment", AccountType.ASSET, AccountNature.CREDIT, "125000", True, False),
    ("130000", "الأصول غير الملموسة", "Intangible Assets", AccountType.ASSET, AccountNature.DEBIT, "100000", False, False),
    ("131000", "البرامج", "Software", AccountType.ASSET, AccountNature.DEBIT, "130000", True, True),
    ("132000", "العلامات التجارية", "Trademarks", AccountType.ASSET, AccountNature.DEBIT, "130000", True, True),
    ("133000", "التراخيص", "Licenses", AccountType.ASSET, AccountNature.DEBIT, "130000", True, True),
    ("134000", "الأصول غير الملموسة الأخرى", "Other Intangible Assets", AccountType.ASSET, AccountNature.DEBIT, "130000", True, True),

    # 200000 الالتزامات
    ("200000", "الالتزامات", "Liabilities", AccountType.LIABILITY, AccountNature.CREDIT, None, False, False),
    ("210000", "الالتزامات المتداولة", "Current Liabilities", AccountType.LIABILITY, AccountNature.CREDIT, "200000", False, False),
    ("211000", "الموردون", "Vendors", AccountType.LIABILITY, AccountNature.CREDIT, "210000", False, False),
    ("211001", "الموردون المحليون", "Local Vendors", AccountType.LIABILITY, AccountNature.CREDIT, "211000", True, True),
    ("211002", "الموردون الدوليون", "International Vendors", AccountType.LIABILITY, AccountNature.CREDIT, "211000", True, True),
    ("211003", "موردون آخرون", "Other Vendors", AccountType.LIABILITY, AccountNature.CREDIT, "211000", True, True),
    ("212000", "أوراق الدفع", "Notes Payable", AccountType.LIABILITY, AccountNature.CREDIT, "210000", True, True),
    ("213000", "المصروفات المستحقة", "Accrued Expenses", AccountType.LIABILITY, AccountNature.CREDIT, "210000", False, False),
    ("213001", "رواتب مستحقة", "Accrued Salaries", AccountType.LIABILITY, AccountNature.CREDIT, "213000", True, True),
    ("213002", "إيجارات مستحقة", "Accrued Rent", AccountType.LIABILITY, AccountNature.CREDIT, "213000", True, True),
    ("213003", "كهرباء مستحقة", "Accrued Electricity", AccountType.LIABILITY, AccountNature.CREDIT, "213000", True, True),
    ("213004", "مصروفات أخرى مستحقة", "Other Accrued Expenses", AccountType.LIABILITY, AccountNature.CREDIT, "213000", True, True),
    ("214000", "الضرائب المستحقة", "Taxes Payable", AccountType.LIABILITY, AccountNature.CREDIT, "210000", False, False),
    ("214001", "ضريبة القيمة المضافة - مخرجات", "Output VAT", AccountType.LIABILITY, AccountNature.CREDIT, "214000", True, True),
    ("214002", "ضريبة القيمة المضافة - تسوية", "VAT Settlement", AccountType.LIABILITY, AccountNature.CREDIT, "214000", True, True),
    ("214003", "ضريبة الاستقطاع", "Withholding Tax", AccountType.LIABILITY, AccountNature.CREDIT, "214000", True, True),
    ("214004", "ضرائب أخرى", "Other Taxes", AccountType.LIABILITY, AccountNature.CREDIT, "214000", True, True),
    ("215000", "الرواتب والموظفين", "Payroll and Employees", AccountType.LIABILITY, AccountNature.CREDIT, "210000", False, False),
    ("215001", "رواتب مستحقة", "Salaries Payable", AccountType.LIABILITY, AccountNature.CREDIT, "215000", True, True),
    ("215002", "مكافآت مستحقة", "Bonuses Payable", AccountType.LIABILITY, AccountNature.CREDIT, "215000", True, True),
    ("215003", "مستحقات موظفين أخرى", "Other Employee Payables", AccountType.LIABILITY, AccountNature.CREDIT, "215000", True, True),
    ("216000", "إيرادات مقدمة", "Deferred Revenue", AccountType.LIABILITY, AccountNature.CREDIT, "210000", False, False),
    ("216001", "دفعات مقدمة من العملاء", "Customer Advances", AccountType.LIABILITY, AccountNature.CREDIT, "216000", True, True),
    ("216002", "إيرادات مؤجلة", "Deferred Income", AccountType.LIABILITY, AccountNature.CREDIT, "216000", True, True),
    ("220000", "الالتزامات غير المتداولة", "Non-current Liabilities", AccountType.LIABILITY, AccountNature.CREDIT, "200000", False, False),
    ("221000", "القروض طويلة الأجل", "Long-term Loans", AccountType.LIABILITY, AccountNature.CREDIT, "220000", True, True),
    ("222000", "التزامات عقود الإيجار", "Lease Liabilities", AccountType.LIABILITY, AccountNature.CREDIT, "220000", True, True),
    ("223000", "مخصص مكافأة نهاية الخدمة", "End of Service Provision", AccountType.LIABILITY, AccountNature.CREDIT, "220000", True, True),
    ("224000", "التزامات طويلة الأجل أخرى", "Other Long-term Liabilities", AccountType.LIABILITY, AccountNature.CREDIT, "220000", True, True),

    # 300000 حقوق الملكية
    ("300000", "حقوق الملكية", "Equity", AccountType.EQUITY, AccountNature.CREDIT, None, False, False),
    ("310000", "رأس المال", "Capital", AccountType.EQUITY, AccountNature.CREDIT, "300000", False, False),
    ("310001", "رأس المال المدفوع", "Paid-in Capital", AccountType.EQUITY, AccountNature.CREDIT, "310000", True, True),
    ("310002", "زيادات رأس المال", "Capital Contributions", AccountType.EQUITY, AccountNature.CREDIT, "310000", True, True),
    ("320000", "الاحتياطيات", "Reserves", AccountType.EQUITY, AccountNature.CREDIT, "300000", False, False),
    ("320001", "الاحتياطي النظامي", "Statutory Reserve", AccountType.EQUITY, AccountNature.CREDIT, "320000", True, False),
    ("320002", "احتياطيات أخرى", "Other Reserves", AccountType.EQUITY, AccountNature.CREDIT, "320000", True, False),
    ("330000", "الأرباح المحتجزة", "Retained Earnings", AccountType.EQUITY, AccountNature.CREDIT, "300000", True, False),
    ("340000", "أرباح / خسائر السنوات السابقة", "Prior Years Profit or Loss", AccountType.EQUITY, AccountNature.CREDIT, "300000", True, False),
    ("350000", "صافي ربح / خسارة السنة", "Current Year Profit or Loss", AccountType.EQUITY, AccountNature.CREDIT, "300000", True, False),
    ("360000", "مسحوبات المالك", "Owner Drawings", AccountType.EQUITY, AccountNature.DEBIT, "300000", True, True),

    # 400000 الإيرادات
    ("400000", "الإيرادات", "Revenue", AccountType.REVENUE, AccountNature.CREDIT, None, False, False),
    ("410000", "إيرادات المبيعات", "Sales Revenue", AccountType.REVENUE, AccountNature.CREDIT, "400000", False, False),
    ("411000", "مبيعات المنتجات", "Product Sales", AccountType.REVENUE, AccountNature.CREDIT, "410000", False, False),
    ("411001", "مبيعات أجهزة", "Device Sales", AccountType.REVENUE, AccountNature.CREDIT, "411000", True, True),
    ("411002", "مبيعات جوالات", "Mobile Phone Sales", AccountType.REVENUE, AccountNature.CREDIT, "411000", True, True),
    ("411003", "مبيعات إكسسوارات", "Accessories Sales", AccountType.REVENUE, AccountNature.CREDIT, "411000", True, True),
    ("411004", "مبيعات قطع غيار", "Spare Parts Sales", AccountType.REVENUE, AccountNature.CREDIT, "411000", True, True),
    ("412000", "مبيعات الخدمات", "Service Sales", AccountType.REVENUE, AccountNature.CREDIT, "410000", False, False),
    ("412001", "خدمات صيانة", "Maintenance Services", AccountType.REVENUE, AccountNature.CREDIT, "412000", True, True),
    ("412002", "خدمات تركيب", "Installation Services", AccountType.REVENUE, AccountNature.CREDIT, "412000", True, True),
    ("412003", "خدمات أخرى", "Other Services", AccountType.REVENUE, AccountNature.CREDIT, "412000", True, True),
    ("420000", "مردودات المبيعات", "Sales Returns", AccountType.REVENUE, AccountNature.DEBIT, "400000", True, True),
    ("430000", "خصومات المبيعات", "Sales Discounts", AccountType.REVENUE, AccountNature.DEBIT, "400000", True, True),
    ("440000", "إيرادات أخرى", "Other Income", AccountType.REVENUE, AccountNature.CREDIT, "400000", False, False),
    ("440001", "إيرادات شحن", "Shipping Income", AccountType.REVENUE, AccountNature.CREDIT, "440000", True, True),
    ("440002", "إيرادات صيانة", "Maintenance Income", AccountType.REVENUE, AccountNature.CREDIT, "440000", True, True),
    ("440003", "إيرادات عمولات", "Commission Income", AccountType.REVENUE, AccountNature.CREDIT, "440000", True, True),
    ("440004", "إيرادات أخرى", "Other Income", AccountType.REVENUE, AccountNature.CREDIT, "440000", True, True),
    ("450000", "أرباح أخرى", "Other Gains", AccountType.REVENUE, AccountNature.CREDIT, "400000", False, False),
    ("450001", "أرباح بيع الأصول", "Gain on Asset Disposal", AccountType.REVENUE, AccountNature.CREDIT, "450000", True, True),
    ("450002", "أرباح فروق العملة", "Foreign Exchange Gain", AccountType.REVENUE, AccountNature.CREDIT, "450000", True, True),

    # 500000 تكلفة المبيعات والمصروفات
    ("500000", "تكلفة المبيعات والمصروفات", "Cost of Sales and Expenses", AccountType.EXPENSE, AccountNature.DEBIT, None, False, False),
    ("510000", "تكلفة المبيعات", "Cost of Sales", AccountType.EXPENSE, AccountNature.DEBIT, "500000", False, False),
    ("511000", "تكلفة البضاعة المباعة", "Cost of Goods Sold", AccountType.EXPENSE, AccountNature.DEBIT, "510000", True, False),
    ("512000", "تكلفة الأجهزة المباعة", "Cost of Devices Sold", AccountType.EXPENSE, AccountNature.DEBIT, "510000", True, False),
    ("513000", "تكلفة الإكسسوارات المباعة", "Cost of Accessories Sold", AccountType.EXPENSE, AccountNature.DEBIT, "510000", True, False),
    ("514000", "تكلفة قطع الغيار", "Cost of Spare Parts Sold", AccountType.EXPENSE, AccountNature.DEBIT, "510000", True, False),
    ("515000", "فروقات المخزون", "Inventory Variances", AccountType.EXPENSE, AccountNature.DEBIT, "510000", True, True),
    ("520000", "مصروفات الموظفين", "Employee Expenses", AccountType.EXPENSE, AccountNature.DEBIT, "500000", False, False),
    ("521000", "الرواتب والأجور", "Salaries and Wages", AccountType.EXPENSE, AccountNature.DEBIT, "520000", True, True),
    ("522000", "التأمينات الاجتماعية", "Social Insurance", AccountType.EXPENSE, AccountNature.DEBIT, "520000", True, True),
    ("523000", "مكافآت", "Bonuses", AccountType.EXPENSE, AccountNature.DEBIT, "520000", True, True),
    ("524000", "بدلات", "Allowances", AccountType.EXPENSE, AccountNature.DEBIT, "520000", True, True),
    ("525000", "تذاكر سفر", "Travel Tickets", AccountType.EXPENSE, AccountNature.DEBIT, "520000", True, True),
    ("526000", "تأمين طبي", "Medical Insurance", AccountType.EXPENSE, AccountNature.DEBIT, "520000", True, True),
    ("527000", "مكافأة نهاية الخدمة", "End of Service Expense", AccountType.EXPENSE, AccountNature.DEBIT, "520000", True, True),
    ("530000", "مصروفات التشغيل", "Operating Expenses", AccountType.EXPENSE, AccountNature.DEBIT, "500000", False, False),
    ("531000", "الإيجار", "Rent Expense", AccountType.EXPENSE, AccountNature.DEBIT, "530000", True, True),
    ("532000", "الكهرباء", "Electricity", AccountType.EXPENSE, AccountNature.DEBIT, "530000", True, True),
    ("533000", "المياه", "Water", AccountType.EXPENSE, AccountNature.DEBIT, "530000", True, True),
    ("534000", "الاتصالات", "Communications", AccountType.EXPENSE, AccountNature.DEBIT, "530000", True, True),
    ("535000", "الإنترنت", "Internet", AccountType.EXPENSE, AccountNature.DEBIT, "530000", True, True),
    ("536000", "الصيانة", "Maintenance", AccountType.EXPENSE, AccountNature.DEBIT, "530000", True, True),
    ("537000", "الأمن والحراسة", "Security and Guarding", AccountType.EXPENSE, AccountNature.DEBIT, "530000", True, True),
    ("540000", "مصروفات البيع والتسويق", "Sales and Marketing Expenses", AccountType.EXPENSE, AccountNature.DEBIT, "500000", False, False),
    ("541000", "الإعلانات", "Advertising", AccountType.EXPENSE, AccountNature.DEBIT, "540000", True, True),
    ("542000", "التسويق", "Marketing", AccountType.EXPENSE, AccountNature.DEBIT, "540000", True, True),
    ("543000", "عمولات المبيعات", "Sales Commissions", AccountType.EXPENSE, AccountNature.DEBIT, "540000", True, True),
    ("544000", "عمولات منصات البيع", "Marketplace Commissions", AccountType.EXPENSE, AccountNature.DEBIT, "540000", True, True),
    ("545000", "الشحن والتوصيل", "Shipping and Delivery", AccountType.EXPENSE, AccountNature.DEBIT, "540000", True, True),
    ("550000", "المصروفات الإدارية", "Administrative Expenses", AccountType.EXPENSE, AccountNature.DEBIT, "500000", False, False),
    ("551000", "القرطاسية", "Stationery", AccountType.EXPENSE, AccountNature.DEBIT, "550000", True, True),
    ("552000", "الضيافة", "Hospitality", AccountType.EXPENSE, AccountNature.DEBIT, "550000", True, True),
    ("553000", "السفر", "Travel", AccountType.EXPENSE, AccountNature.DEBIT, "550000", True, True),
    ("554000", "الاستشارات", "Consulting", AccountType.EXPENSE, AccountNature.DEBIT, "550000", True, True),
    ("555000", "الخدمات المهنية", "Professional Services", AccountType.EXPENSE, AccountNature.DEBIT, "550000", True, True),
    ("556000", "البرامج والاشتراكات", "Software and Subscriptions", AccountType.EXPENSE, AccountNature.DEBIT, "550000", True, True),
    ("560000", "مصروفات مالية", "Financial Expenses", AccountType.EXPENSE, AccountNature.DEBIT, "500000", False, False),
    ("561000", "رسوم بنكية", "Bank Fees", AccountType.EXPENSE, AccountNature.DEBIT, "560000", True, True),
    ("562000", "عمولات بنكية", "Bank Commissions", AccountType.EXPENSE, AccountNature.DEBIT, "560000", True, True),
    ("563000", "فروقات عملة", "Foreign Exchange Loss", AccountType.EXPENSE, AccountNature.DEBIT, "560000", True, True),
    ("564000", "تكاليف تمويل", "Finance Costs", AccountType.EXPENSE, AccountNature.DEBIT, "560000", True, True),
    ("570000", "الاستهلاك والإطفاء", "Depreciation and Amortization", AccountType.EXPENSE, AccountNature.DEBIT, "500000", False, False),
    ("571000", "استهلاك المباني", "Building Depreciation", AccountType.EXPENSE, AccountNature.DEBIT, "570000", True, False),
    ("572000", "استهلاك الأثاث", "Furniture Depreciation", AccountType.EXPENSE, AccountNature.DEBIT, "570000", True, False),
    ("573000", "استهلاك المركبات", "Vehicle Depreciation", AccountType.EXPENSE, AccountNature.DEBIT, "570000", True, False),
    ("574000", "استهلاك الأجهزة", "Equipment Depreciation", AccountType.EXPENSE, AccountNature.DEBIT, "570000", True, False),
    ("580000", "مصروفات أخرى", "Other Expenses", AccountType.EXPENSE, AccountNature.DEBIT, "500000", False, False),
    ("581000", "خسائر بيع الأصول", "Loss on Asset Disposal", AccountType.EXPENSE, AccountNature.DEBIT, "580000", True, True),
    ("582000", "غرامات ومخالفات", "Fines and Penalties", AccountType.EXPENSE, AccountNature.DEBIT, "580000", True, True),
    ("583000", "تبرعات", "Donations", AccountType.EXPENSE, AccountNature.DEBIT, "580000", True, True),
    ("584000", "مصروفات أخرى", "Other Expenses", AccountType.EXPENSE, AccountNature.DEBIT, "580000", True, True),
]


# مفاتيح الربط التشغيلية: تستخدم الحسابات النهائية فقط. الحسابات المتخصصة
# حسب فئة الصنف ستضاف في الدفعة التالية؛ هذه مفاتيح افتراضية قابلة للتغيير من الواجهة.
DEFAULT_MAPPING_CODES: dict[str, str] = {
    "default_cash": "111001",
    "default_bank": "112001",
    "default_card": "112001",
    "default_wallet": "112001",
    "default_ar": "113001",
    "inventory": "114001",
    "vat_input": "115002",
    "employee_advances": "117001",
    "rep_collections": "117002",
    "default_ap": "211001",
    "vat_output": "214001",
    "payroll_payable": "215001",
    "accrued_expenses": "213004",
    "capital": "310001",
    "sales_goods": "411001",
    "sales_services": "412003",
    "sales_returns": "420000",
    "sales_discounts": "430000",
    "other_income": "440004",
    "cogs_goods": "511000",
    "cost_services": "584000",
    "payroll_expense": "521000",
    "operating_expenses": "584000",
    "inventory_adjustment_gain": "440004",
    "inventory_adjustment_loss": "515000",
}

REQUIRED_MAPPING_KEYS: tuple[str, ...] = (
    "default_cash", "default_ar", "inventory", "vat_input", "default_ap",
    "vat_output", "sales_goods", "cogs_goods",
)
