"""الشجرة الافتراضية المنقحة ذات الأكواد القصيرة كما اعتمدها المستخدم."""
from app.models.accounting import AccountNature, AccountType

# code, الاسم العربي، الاسم الإنجليزي، النوع، الطبيعة، رمز الأب، قابل للقيد، يسمح بقيد مباشر
SHORT_DEFAULT_CHART = [
    ('01', 'الأصول', 'الأصول', AccountType.ASSET, AccountNature.DEBIT, None, False, False),
    ('011', 'الأصول المتداولة', 'الأصول المتداولة', AccountType.ASSET, AccountNature.DEBIT, '01', False, False),
    ('0111', 'النقدية', 'النقدية', AccountType.ASSET, AccountNature.DEBIT, '011', False, False),
    ('01111', 'الصندوق الرئيسي', 'الصندوق الرئيسي', AccountType.ASSET, AccountNature.DEBIT, '0111', True, True),
    ('01112', 'صندوق الفرع', 'صندوق الفرع', AccountType.ASSET, AccountNature.DEBIT, '0111', True, True),
    ('01113', 'عهد نقدية', 'عهد نقدية', AccountType.ASSET, AccountNature.DEBIT, '0111', True, True),
    ('0112', 'البنوك', 'البنوك', AccountType.ASSET, AccountNature.DEBIT, '011', False, False),
    ('01121', 'البنك - الحساب الجاري', 'البنك - الحساب الجاري', AccountType.ASSET, AccountNature.DEBIT, '0112', True, True),
    ('01122', 'البنك - حساب التوفير', 'البنك - حساب التوفير', AccountType.ASSET, AccountNature.DEBIT, '0112', True, True),
    ('01123', 'بنك الراجحي', 'بنك الراجحي', AccountType.ASSET, AccountNature.DEBIT, '0112', True, True),
    ('01124', 'البنك الأهلي', 'البنك الأهلي', AccountType.ASSET, AccountNature.DEBIT, '0112', True, True),
    ('01125', 'بنك الرياض', 'بنك الرياض', AccountType.ASSET, AccountNature.DEBIT, '0112', True, True),
    ('0113', 'العملاء والذمم المدينة', 'العملاء والذمم المدينة', AccountType.ASSET, AccountNature.DEBIT, '011', False, False),
    ('01131', 'العملاء', 'العملاء', AccountType.ASSET, AccountNature.DEBIT, '0113', False, False),
    ('011311', 'عملاء المندوب - وليد / جدة', 'عملاء المندوب - وليد / جدة', AccountType.ASSET, AccountNature.DEBIT, '01131', False, False),
    ('01131101', 'الحسيني للاتصالات', 'الحسيني للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131102', 'الرائد', 'الرائد', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131103', 'الشامخ للاتصالات', 'الشامخ للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131104', 'المتكامل', 'المتكامل', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131105', 'المدهش', 'المدهش', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131106', 'المغربي الحمدانية', 'المغربي الحمدانية', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131107', 'النخبة أم القرى', 'النخبة أم القرى', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131108', 'الواليد للاتصالات', 'الواليد للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131109', 'ايلين للاتصالات', 'ايلين للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131110', 'بصمة 1', 'بصمة 1', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131111', 'بن مقبول الطائف', 'بن مقبول الطائف', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131112', 'جوهرة رابغ', 'جوهرة رابغ', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131113', 'روكتن', 'روكتن', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131114', 'زوز للاتصالات', 'زوز للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131115', 'زون فون', 'زون فون', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131116', 'شاشة ولمسة', 'شاشة ولمسة', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131117', 'شركة هدف المتميزة التجارية', 'شركة هدف المتميزة التجارية', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131118', 'كيان', 'كيان', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131119', 'مالك الجوري مشهور', 'مالك الجوري مشهور', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131120', 'مداد للاتصال', 'مداد للاتصال', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131121', 'مسكة الجوال الحمدانية', 'مسكة الجوال الحمدانية', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131122', 'مؤسسة عمر هادي عمر سوادي التجارية', 'مؤسسة عمر هادي عمر سوادي التجارية', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131123', 'واي فاي رابغ', 'واي فاي رابغ', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131124', 'ون توب', 'ون توب', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131125', 'الاتصال السريع', 'الاتصال السريع', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131126', 'الباشا فون', 'الباشا فون', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131127', 'الباهر للاتصالات', 'الباهر للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131128', 'الريان (السنابل)', 'الريان (السنابل)', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131129', 'المغربي مدائن الفهد', 'المغربي مدائن الفهد', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131130', 'ركن الحداد الحمدانية', 'ركن الحداد الحمدانية', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131131', 'عالم التقنية الحديثة', 'عالم التقنية الحديثة', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131132', 'محل الخيال (مدائن الفهد)', 'محل الخيال (مدائن الفهد)', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131133', 'مؤسسة عنقا عتيق بخيت السلمي للاتصالات', 'مؤسسة عنقا عتيق بخيت السلمي للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131134', 'مؤسسة قمة التطوير للألعاب الأطفال', 'مؤسسة قمة التطوير للألعاب الأطفال', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131135', 'مؤسسة محمد شاكر (نيوم)', 'مؤسسة محمد شاكر (نيوم)', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('01131136', 'مؤسسة هديل علي عيس محسني للتجارة', 'مؤسسة هديل علي عيس محسني للتجارة', AccountType.ASSET, AccountNature.DEBIT, '011311', True, True),
    ('011312', 'عملاء المندوب - أحمد / الرياض', 'عملاء المندوب - أحمد / الرياض', AccountType.ASSET, AccountNature.DEBIT, '01131', False, False),
    ('01131201', 'اختيار الهاتف', 'اختيار الهاتف', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131202', 'أفراد مقبل للاتصالات', 'أفراد مقبل للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131203', 'الإيطالي', 'الإيطالي', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131204', 'الفخامة الرقمية', 'الفخامة الرقمية', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131205', 'الفخامة للاتصالات', 'الفخامة للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131206', 'بحر الجوال', 'بحر الجوال', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131207', 'بحر الجوال عزوز', 'بحر الجوال عزوز', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131208', 'بصمة العاصمة', 'بصمة العاصمة', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131209', 'جوال الأساس', 'جوال الأساس', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131210', 'خط البيدق', 'خط البيدق', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131211', 'درة دلع جوالي', 'درة دلع جوالي', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131212', 'زاوية سعدون', 'زاوية سعدون', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131213', 'شركة نجاح وأكثر', 'شركة نجاح وأكثر', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131214', 'صحراء نجد', 'صحراء نجد', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131215', 'عالم المشاهير للاتصالات', 'عالم المشاهير للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131216', 'كود 3', 'كود 3', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131217', 'لمعة أصيل', 'لمعة أصيل', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131218', 'معاني حمود العنزي', 'معاني حمود العنزي', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131219', 'مؤسسة رشيد حسين حلف العثماني', 'مؤسسة رشيد حسين حلف العثماني', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131220', 'مؤسسة عثمان حمدان الحربي', 'مؤسسة عثمان حمدان الحربي', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131221', 'مؤسسة كيان العزيزية الرياض', 'مؤسسة كيان العزيزية الرياض', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131222', 'نترا تيك', 'نترا تيك', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131223', 'نجمة المربع', 'نجمة المربع', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131224', 'نسيم الخليج', 'نسيم الخليج', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131225', 'همسات تقني', 'همسات تقني', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('01131226', 'واي فاي النهضة', 'واي فاي النهضة', AccountType.ASSET, AccountNature.DEBIT, '011312', True, True),
    ('011313', 'عملاء المندوب - محمد / جيزان', 'عملاء المندوب - محمد / جيزان', AccountType.ASSET, AccountNature.DEBIT, '01131', False, False),
    ('01131301', 'الجزيرة', 'الجزيرة', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131302', 'الشرفي', 'الشرفي', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131303', 'الضمان الذهبي', 'الضمان الذهبي', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131304', 'العربي فور', 'العربي فور', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131305', 'المتحدون', 'المتحدون', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131306', 'بركات الشبكات', 'بركات الشبكات', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131307', 'بريق الهاتف', 'بريق الهاتف', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131308', 'بصمة بلس', 'بصمة بلس', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131309', 'بصمة ميلان', 'بصمة ميلان', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131310', 'بن جنير', 'بن جنير', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131311', 'تميز وابداع', 'تميز وابداع', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131312', 'ركن الشعار', 'ركن الشعار', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131313', 'روائع الخليج', 'روائع الخليج', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131314', 'صقور الجو', 'صقور الجو', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131315', 'فنون', 'فنون', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131316', 'لمسة للاتصالات', 'لمسة للاتصالات', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131317', 'لهم', 'لهم', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131318', 'ماي وفنون', 'ماي وفنون', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131319', 'متصدر الجوال', 'متصدر الجوال', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131320', 'مؤسسة عبده محمد علي', 'مؤسسة عبده محمد علي', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01131321', 'وليد منصور', 'وليد منصور', AccountType.ASSET, AccountNature.DEBIT, '011313', True, True),
    ('01132', 'عملاء آجلة', 'عملاء آجلة', AccountType.ASSET, AccountNature.DEBIT, '0113', True, True),
    ('01133', 'شيكات تحت التحصيل', 'شيكات تحت التحصيل', AccountType.ASSET, AccountNature.DEBIT, '0113', True, True),
    ('01134', 'مخصص الديون المشكوك فيها', 'مخصص الديون المشكوك فيها', AccountType.ASSET, AccountNature.CREDIT, '0113', True, True),
    ('0114', 'المخزون', 'المخزون', AccountType.ASSET, AccountNature.DEBIT, '011', False, False),
    ('01141', 'مخزون البضائع', 'مخزون البضائع', AccountType.ASSET, AccountNature.DEBIT, '0114', True, True),
    ('01142', 'مخزون الأجهزة', 'مخزون الأجهزة', AccountType.ASSET, AccountNature.DEBIT, '0114', True, True),
    ('01143', 'مخزون قطع الغيار', 'مخزون قطع الغيار', AccountType.ASSET, AccountNature.DEBIT, '0114', True, True),
    ('01144', 'مخزون الإكسسوارات', 'مخزون الإكسسوارات', AccountType.ASSET, AccountNature.DEBIT, '0114', True, True),
    ('01145', 'بضاعة بالطريق', 'بضاعة بالطريق', AccountType.ASSET, AccountNature.DEBIT, '0114', True, True),
    ('01146', 'مخزون تالف', 'مخزون تالف', AccountType.ASSET, AccountNature.DEBIT, '0114', True, True),
    ('0115', 'الضرائب والذمم الحكومية', 'الضرائب والذمم الحكومية', AccountType.ASSET, AccountNature.DEBIT, '011', False, False),
    ('01151', 'ضريبة القيمة المضافة - مدخلات', 'ضريبة القيمة المضافة - مدخلات', AccountType.ASSET, AccountNature.DEBIT, '0115', True, True),
    ('01152', 'ضريبة مدخلات قابلة للاسترداد', 'ضريبة مدخلات قابلة للاسترداد', AccountType.ASSET, AccountNature.DEBIT, '0115', True, True),
    ('01153', 'أرصدة حكومية مدينة', 'أرصدة حكومية مدينة', AccountType.ASSET, AccountNature.DEBIT, '0115', True, True),
    ('0116', 'المصروفات المدفوعة مقدماً', 'المصروفات المدفوعة مقدماً', AccountType.ASSET, AccountNature.DEBIT, '011', False, False),
    ('01161', 'إيجار مدفوع مقدماً', 'إيجار مدفوع مقدماً', AccountType.ASSET, AccountNature.DEBIT, '0116', True, True),
    ('01162', 'تأمين مدفوع مقدماً', 'تأمين مدفوع مقدماً', AccountType.ASSET, AccountNature.DEBIT, '0116', True, True),
    ('01163', 'اشتراكات مدفوعة مقدماً', 'اشتراكات مدفوعة مقدماً', AccountType.ASSET, AccountNature.DEBIT, '0116', True, True),
    ('0117', 'أصول متداولة أخرى', 'أصول متداولة أخرى', AccountType.ASSET, AccountNature.DEBIT, '011', False, False),
    ('01171', 'سلف الموظفين', 'سلف الموظفين', AccountType.ASSET, AccountNature.DEBIT, '0117', True, True),
    ('01172', 'عهد الموظفين', 'عهد الموظفين', AccountType.ASSET, AccountNature.DEBIT, '0117', True, True),
    ('01173', 'تأمينات لدى الغير', 'تأمينات لدى الغير', AccountType.ASSET, AccountNature.DEBIT, '0117', True, True),
    ('012', 'الأصول غير المتداولة', 'الأصول غير المتداولة', AccountType.ASSET, AccountNature.DEBIT, '01', False, False),
    ('0121', 'الممتلكات والمباني', 'الممتلكات والمباني', AccountType.ASSET, AccountNature.DEBIT, '012', False, False),
    ('01211', 'الأراضي', 'الأراضي', AccountType.ASSET, AccountNature.DEBIT, '0121', True, True),
    ('01212', 'المباني', 'المباني', AccountType.ASSET, AccountNature.DEBIT, '0121', True, True),
    ('01213', 'تحسينات المباني', 'تحسينات المباني', AccountType.ASSET, AccountNature.DEBIT, '0121', True, True),
    ('0122', 'الأثاث والتجهيزات', 'الأثاث والتجهيزات', AccountType.ASSET, AccountNature.DEBIT, '012', False, False),
    ('01221', 'الأثاث', 'الأثاث', AccountType.ASSET, AccountNature.DEBIT, '0122', True, True),
    ('01222', 'تجهيزات المعارض', 'تجهيزات المعارض', AccountType.ASSET, AccountNature.DEBIT, '0122', True, True),
    ('01223', 'ديكورات', 'ديكورات', AccountType.ASSET, AccountNature.DEBIT, '0122', True, True),
    ('0123', 'المركبات', 'المركبات', AccountType.ASSET, AccountNature.DEBIT, '012', False, False),
    ('01231', 'سيارات', 'سيارات', AccountType.ASSET, AccountNature.DEBIT, '0123', True, True),
    ('01232', 'مركبات نقل', 'مركبات نقل', AccountType.ASSET, AccountNature.DEBIT, '0123', True, True),
    ('01233', 'دراجات', 'دراجات', AccountType.ASSET, AccountNature.DEBIT, '0123', True, True),
    ('0124', 'الأجهزة والمعدات', 'الأجهزة والمعدات', AccountType.ASSET, AccountNature.DEBIT, '012', False, False),
    ('01241', 'أجهزة كمبيوتر', 'أجهزة كمبيوتر', AccountType.ASSET, AccountNature.DEBIT, '0124', True, True),
    ('01242', 'معدات', 'معدات', AccountType.ASSET, AccountNature.DEBIT, '0124', True, True),
    ('01243', 'أجهزة مكتبية', 'أجهزة مكتبية', AccountType.ASSET, AccountNature.DEBIT, '0124', True, True),
    ('0125', 'مجمع الاستهلاك', 'مجمع الاستهلاك', AccountType.ASSET, AccountNature.CREDIT, '012', False, False),
    ('01251', 'مجمع استهلاك المباني', 'مجمع استهلاك المباني', AccountType.ASSET, AccountNature.CREDIT, '0125', True, True),
    ('01252', 'مجمع استهلاك الأثاث', 'مجمع استهلاك الأثاث', AccountType.ASSET, AccountNature.CREDIT, '0125', True, True),
    ('01253', 'مجمع استهلاك المركبات', 'مجمع استهلاك المركبات', AccountType.ASSET, AccountNature.CREDIT, '0125', True, True),
    ('01254', 'مجمع استهلاك الأجهزة', 'مجمع استهلاك الأجهزة', AccountType.ASSET, AccountNature.CREDIT, '0125', True, True),
    ('013', 'الأصول غير الملموسة', 'الأصول غير الملموسة', AccountType.ASSET, AccountNature.DEBIT, '01', False, False),
    ('0131', 'البرامج', 'البرامج', AccountType.ASSET, AccountNature.DEBIT, '013', True, True),
    ('0132', 'العلامات التجارية', 'العلامات التجارية', AccountType.ASSET, AccountNature.DEBIT, '013', True, True),
    ('0133', 'التراخيص', 'التراخيص', AccountType.ASSET, AccountNature.DEBIT, '013', True, True),
    ('0134', 'الأصول غير الملموسة الأخرى', 'الأصول غير الملموسة الأخرى', AccountType.ASSET, AccountNature.DEBIT, '013', True, True),
    ('02', 'الالتزامات', 'الالتزامات', AccountType.LIABILITY, AccountNature.CREDIT, None, False, False),
    ('021', 'الالتزامات المتداولة', 'الالتزامات المتداولة', AccountType.LIABILITY, AccountNature.CREDIT, '02', False, False),
    ('0211', 'الموردون', 'الموردون', AccountType.LIABILITY, AccountNature.CREDIT, '021', False, False),
    ('02111', 'الموردون المحليون', 'الموردون المحليون', AccountType.LIABILITY, AccountNature.CREDIT, '0211', True, True),
    ('02112', 'الموردون الدوليون', 'الموردون الدوليون', AccountType.LIABILITY, AccountNature.CREDIT, '0211', True, True),
    ('02113', 'موردون آخرون', 'موردون آخرون', AccountType.LIABILITY, AccountNature.CREDIT, '0211', True, True),
    ('0212', 'أوراق الدفع', 'أوراق الدفع', AccountType.LIABILITY, AccountNature.CREDIT, '021', True, True),
    ('0213', 'المصروفات المستحقة', 'المصروفات المستحقة', AccountType.LIABILITY, AccountNature.CREDIT, '021', False, False),
    ('02131', 'رواتب مستحقة', 'رواتب مستحقة', AccountType.LIABILITY, AccountNature.CREDIT, '0213', True, True),
    ('02132', 'إيجارات مستحقة', 'إيجارات مستحقة', AccountType.LIABILITY, AccountNature.CREDIT, '0213', True, True),
    ('02133', 'كهرباء مستحقة', 'كهرباء مستحقة', AccountType.LIABILITY, AccountNature.CREDIT, '0213', True, True),
    ('02134', 'مصروفات أخرى مستحقة', 'مصروفات أخرى مستحقة', AccountType.LIABILITY, AccountNature.CREDIT, '0213', True, True),
    ('0214', 'الضرائب المستحقة', 'الضرائب المستحقة', AccountType.LIABILITY, AccountNature.CREDIT, '021', False, False),
    ('02141', 'ضريبة القيمة المضافة - مخرجات', 'ضريبة القيمة المضافة - مخرجات', AccountType.LIABILITY, AccountNature.CREDIT, '0214', True, True),
    ('02142', 'ضريبة القيمة المضافة - تسوية', 'ضريبة القيمة المضافة - تسوية', AccountType.LIABILITY, AccountNature.CREDIT, '0214', True, True),
    ('02143', 'ضريبة الاستقطاع', 'ضريبة الاستقطاع', AccountType.LIABILITY, AccountNature.CREDIT, '0214', True, True),
    ('02144', 'ضرائب أخرى', 'ضرائب أخرى', AccountType.LIABILITY, AccountNature.CREDIT, '0214', True, True),
    ('0215', 'الرواتب والموظفين', 'الرواتب والموظفين', AccountType.LIABILITY, AccountNature.CREDIT, '021', False, False),
    ('02151', 'رواتب مستحقة', 'رواتب مستحقة', AccountType.LIABILITY, AccountNature.CREDIT, '0215', True, True),
    ('02152', 'مكافآت مستحقة', 'مكافآت مستحقة', AccountType.LIABILITY, AccountNature.CREDIT, '0215', True, True),
    ('02153', 'مستحقات موظفين أخرى', 'مستحقات موظفين أخرى', AccountType.LIABILITY, AccountNature.CREDIT, '0215', True, True),
    ('0216', 'إيرادات مقدمة', 'إيرادات مقدمة', AccountType.LIABILITY, AccountNature.CREDIT, '021', False, False),
    ('02161', 'دفعات مقدمة من العملاء', 'دفعات مقدمة من العملاء', AccountType.LIABILITY, AccountNature.CREDIT, '0216', True, True),
    ('02162', 'إيرادات مؤجلة', 'إيرادات مؤجلة', AccountType.LIABILITY, AccountNature.CREDIT, '0216', True, True),
    ('022', 'الالتزامات غير المتداولة', 'الالتزامات غير المتداولة', AccountType.LIABILITY, AccountNature.CREDIT, '02', False, False),
    ('0221', 'القروض طويلة الأجل', 'القروض طويلة الأجل', AccountType.LIABILITY, AccountNature.CREDIT, '022', True, True),
    ('0222', 'التزامات عقود الإيجار', 'التزامات عقود الإيجار', AccountType.LIABILITY, AccountNature.CREDIT, '022', True, True),
    ('0223', 'مخصص مكافأة نهاية الخدمة', 'مخصص مكافأة نهاية الخدمة', AccountType.LIABILITY, AccountNature.CREDIT, '022', True, True),
    ('0224', 'التزامات طويلة الأجل أخرى', 'التزامات طويلة الأجل أخرى', AccountType.LIABILITY, AccountNature.CREDIT, '022', True, True),
    ('03', 'حقوق الملكية', 'حقوق الملكية', AccountType.EQUITY, AccountNature.CREDIT, None, False, False),
    ('031', 'رأس المال', 'رأس المال', AccountType.EQUITY, AccountNature.CREDIT, '03', False, False),
    ('0311', 'رأس المال المدفوع', 'رأس المال المدفوع', AccountType.EQUITY, AccountNature.CREDIT, '031', True, True),
    ('0312', 'زيادات رأس المال', 'زيادات رأس المال', AccountType.EQUITY, AccountNature.CREDIT, '031', True, True),
    ('032', 'الاحتياطيات', 'الاحتياطيات', AccountType.EQUITY, AccountNature.CREDIT, '03', False, False),
    ('0321', 'الاحتياطي النظامي', 'الاحتياطي النظامي', AccountType.EQUITY, AccountNature.CREDIT, '032', True, True),
    ('0322', 'احتياطيات أخرى', 'احتياطيات أخرى', AccountType.EQUITY, AccountNature.CREDIT, '032', True, True),
    ('033', 'الأرباح المحتجزة', 'الأرباح المحتجزة', AccountType.EQUITY, AccountNature.CREDIT, '03', True, True),
    ('034', 'أرباح / خسائر السنوات السابقة', 'أرباح / خسائر السنوات السابقة', AccountType.EQUITY, AccountNature.CREDIT, '03', True, True),
    ('035', 'صافي ربح / خسارة السنة', 'صافي ربح / خسارة السنة', AccountType.EQUITY, AccountNature.CREDIT, '03', True, True),
    ('036', 'مسحوبات المالك', 'مسحوبات المالك', AccountType.EQUITY, AccountNature.CREDIT, '03', True, True),
    ('04', 'الإيرادات', 'الإيرادات', AccountType.REVENUE, AccountNature.CREDIT, None, False, False),
    ('041', 'إيرادات المبيعات', 'إيرادات المبيعات', AccountType.REVENUE, AccountNature.CREDIT, '04', False, False),
    ('0411', 'مبيعات المنتجات', 'مبيعات المنتجات', AccountType.REVENUE, AccountNature.CREDIT, '041', False, False),
    ('04111', 'مبيعات أجهزة', 'مبيعات أجهزة', AccountType.REVENUE, AccountNature.CREDIT, '0411', True, True),
    ('04112', 'مبيعات جوالات', 'مبيعات جوالات', AccountType.REVENUE, AccountNature.CREDIT, '0411', True, True),
    ('04113', 'مبيعات إكسسوارات', 'مبيعات إكسسوارات', AccountType.REVENUE, AccountNature.CREDIT, '0411', True, True),
    ('04114', 'مبيعات قطع غيار', 'مبيعات قطع غيار', AccountType.REVENUE, AccountNature.CREDIT, '0411', True, True),
    ('0412', 'مبيعات الخدمات', 'مبيعات الخدمات', AccountType.REVENUE, AccountNature.CREDIT, '041', False, False),
    ('04121', 'خدمات صيانة', 'خدمات صيانة', AccountType.REVENUE, AccountNature.CREDIT, '0412', True, True),
    ('04122', 'خدمات تركيب', 'خدمات تركيب', AccountType.REVENUE, AccountNature.CREDIT, '0412', True, True),
    ('04123', 'خدمات أخرى', 'خدمات أخرى', AccountType.REVENUE, AccountNature.CREDIT, '0412', True, True),
    ('042', 'مردودات المبيعات', 'مردودات المبيعات', AccountType.REVENUE, AccountNature.CREDIT, '04', True, True),
    ('043', 'خصومات المبيعات', 'خصومات المبيعات', AccountType.REVENUE, AccountNature.CREDIT, '04', True, True),
    ('044', 'إيرادات أخرى', 'إيرادات أخرى', AccountType.REVENUE, AccountNature.CREDIT, '04', False, False),
    ('0441', 'إيرادات شحن', 'إيرادات شحن', AccountType.REVENUE, AccountNature.CREDIT, '044', True, True),
    ('0442', 'إيرادات صيانة', 'إيرادات صيانة', AccountType.REVENUE, AccountNature.CREDIT, '044', True, True),
    ('0443', 'إيرادات عمولات', 'إيرادات عمولات', AccountType.REVENUE, AccountNature.CREDIT, '044', True, True),
    ('0444', 'إيرادات أخرى', 'إيرادات أخرى', AccountType.REVENUE, AccountNature.CREDIT, '044', True, True),
    ('045', 'أرباح أخرى', 'أرباح أخرى', AccountType.REVENUE, AccountNature.CREDIT, '04', False, False),
    ('0451', 'أرباح بيع الأصول', 'أرباح بيع الأصول', AccountType.REVENUE, AccountNature.CREDIT, '045', True, True),
    ('0452', 'أرباح فروق العملة', 'أرباح فروق العملة', AccountType.REVENUE, AccountNature.CREDIT, '045', True, True),
    ('05', 'تكلفة المبيعات والمصروفات', 'تكلفة المبيعات والمصروفات', AccountType.EXPENSE, AccountNature.DEBIT, None, False, False),
    ('051', 'تكلفة المبيعات', 'تكلفة المبيعات', AccountType.EXPENSE, AccountNature.DEBIT, '05', False, False),
    ('0511', 'تكلفة البضاعة المباعة', 'تكلفة البضاعة المباعة', AccountType.EXPENSE, AccountNature.DEBIT, '051', True, True),
    ('0512', 'تكلفة الأجهزة المباعة', 'تكلفة الأجهزة المباعة', AccountType.EXPENSE, AccountNature.DEBIT, '051', True, True),
    ('0513', 'تكلفة الإكسسوارات المباعة', 'تكلفة الإكسسوارات المباعة', AccountType.EXPENSE, AccountNature.DEBIT, '051', True, True),
    ('0514', 'تكلفة قطع الغيار', 'تكلفة قطع الغيار', AccountType.EXPENSE, AccountNature.DEBIT, '051', True, True),
    ('0515', 'فروقات المخزون', 'فروقات المخزون', AccountType.EXPENSE, AccountNature.DEBIT, '051', True, True),
    ('052', 'مصروفات الموظفين', 'مصروفات الموظفين', AccountType.EXPENSE, AccountNature.DEBIT, '05', False, False),
    ('0521', 'الرواتب والأجور', 'الرواتب والأجور', AccountType.EXPENSE, AccountNature.DEBIT, '052', True, True),
    ('0522', 'التأمينات الاجتماعية', 'التأمينات الاجتماعية', AccountType.EXPENSE, AccountNature.DEBIT, '052', True, True),
    ('0523', 'مكافآت', 'مكافآت', AccountType.EXPENSE, AccountNature.DEBIT, '052', True, True),
    ('0524', 'بدلات', 'بدلات', AccountType.EXPENSE, AccountNature.DEBIT, '052', True, True),
    ('0525', 'تذاكر سفر', 'تذاكر سفر', AccountType.EXPENSE, AccountNature.DEBIT, '052', True, True),
    ('0526', 'تأمين طبي', 'تأمين طبي', AccountType.EXPENSE, AccountNature.DEBIT, '052', True, True),
    ('0527', 'مكافأة نهاية الخدمة', 'مكافأة نهاية الخدمة', AccountType.EXPENSE, AccountNature.DEBIT, '052', True, True),
    ('053', 'مصروفات التشغيل', 'مصروفات التشغيل', AccountType.EXPENSE, AccountNature.DEBIT, '05', False, False),
    ('0531', 'الإيجار', 'الإيجار', AccountType.EXPENSE, AccountNature.DEBIT, '053', True, True),
    ('0532', 'الكهرباء', 'الكهرباء', AccountType.EXPENSE, AccountNature.DEBIT, '053', True, True),
    ('0533', 'المياه', 'المياه', AccountType.EXPENSE, AccountNature.DEBIT, '053', True, True),
    ('0534', 'الاتصالات', 'الاتصالات', AccountType.EXPENSE, AccountNature.DEBIT, '053', True, True),
    ('0535', 'الإنترنت', 'الإنترنت', AccountType.EXPENSE, AccountNature.DEBIT, '053', True, True),
    ('0536', 'الصيانة', 'الصيانة', AccountType.EXPENSE, AccountNature.DEBIT, '053', True, True),
    ('0537', 'الأمن والحراسة', 'الأمن والحراسة', AccountType.EXPENSE, AccountNature.DEBIT, '053', True, True),
    ('054', 'مصروفات البيع والتسويق', 'مصروفات البيع والتسويق', AccountType.EXPENSE, AccountNature.DEBIT, '05', False, False),
    ('0541', 'الإعلانات', 'الإعلانات', AccountType.EXPENSE, AccountNature.DEBIT, '054', True, True),
    ('0542', 'التسويق', 'التسويق', AccountType.EXPENSE, AccountNature.DEBIT, '054', True, True),
    ('0543', 'عمولات المبيعات', 'عمولات المبيعات', AccountType.EXPENSE, AccountNature.DEBIT, '054', True, True),
    ('0544', 'عمولات منصات البيع', 'عمولات منصات البيع', AccountType.EXPENSE, AccountNature.DEBIT, '054', True, True),
    ('0545', 'الشحن والتوصيل', 'الشحن والتوصيل', AccountType.EXPENSE, AccountNature.DEBIT, '054', True, True),
    ('055', 'المصروفات الإدارية', 'المصروفات الإدارية', AccountType.EXPENSE, AccountNature.DEBIT, '05', False, False),
    ('0551', 'القرطاسية', 'القرطاسية', AccountType.EXPENSE, AccountNature.DEBIT, '055', True, True),
    ('0552', 'الضيافة', 'الضيافة', AccountType.EXPENSE, AccountNature.DEBIT, '055', True, True),
    ('0553', 'السفر', 'السفر', AccountType.EXPENSE, AccountNature.DEBIT, '055', True, True),
    ('0554', 'الاستشارات', 'الاستشارات', AccountType.EXPENSE, AccountNature.DEBIT, '055', True, True),
    ('0555', 'الخدمات المهنية', 'الخدمات المهنية', AccountType.EXPENSE, AccountNature.DEBIT, '055', True, True),
    ('0556', 'البرامج والاشتراكات', 'البرامج والاشتراكات', AccountType.EXPENSE, AccountNature.DEBIT, '055', True, True),
    ('056', 'مصروفات مالية', 'مصروفات مالية', AccountType.EXPENSE, AccountNature.DEBIT, '05', False, False),
    ('0561', 'رسوم بنكية', 'رسوم بنكية', AccountType.EXPENSE, AccountNature.DEBIT, '056', True, True),
    ('0562', 'عمولات بنكية', 'عمولات بنكية', AccountType.EXPENSE, AccountNature.DEBIT, '056', True, True),
    ('0563', 'فروقات عملة', 'فروقات عملة', AccountType.EXPENSE, AccountNature.DEBIT, '056', True, True),
    ('0564', 'تكاليف تمويل', 'تكاليف تمويل', AccountType.EXPENSE, AccountNature.DEBIT, '056', True, True),
    ('057', 'الاستهلاك والإطفاء', 'الاستهلاك والإطفاء', AccountType.EXPENSE, AccountNature.DEBIT, '05', False, False),
    ('0571', 'استهلاك المباني', 'استهلاك المباني', AccountType.EXPENSE, AccountNature.DEBIT, '057', True, True),
    ('0572', 'استهلاك الأثاث', 'استهلاك الأثاث', AccountType.EXPENSE, AccountNature.DEBIT, '057', True, True),
    ('0573', 'استهلاك المركبات', 'استهلاك المركبات', AccountType.EXPENSE, AccountNature.DEBIT, '057', True, True),
    ('0574', 'استهلاك الأجهزة', 'استهلاك الأجهزة', AccountType.EXPENSE, AccountNature.DEBIT, '057', True, True),
    ('058', 'مصروفات أخرى', 'مصروفات أخرى', AccountType.EXPENSE, AccountNature.DEBIT, '05', False, False),
    ('0581', 'خسائر بيع الأصول', 'خسائر بيع الأصول', AccountType.EXPENSE, AccountNature.DEBIT, '058', True, True),
    ('0582', 'غرامات ومخالفات', 'غرامات ومخالفات', AccountType.EXPENSE, AccountNature.DEBIT, '058', True, True),
    ('0583', 'تبرعات', 'تبرعات', AccountType.EXPENSE, AccountNature.DEBIT, '058', True, True),
    ('0584', 'مصروفات أخرى', 'مصروفات أخرى', AccountType.EXPENSE, AccountNature.DEBIT, '058', True, True),
]

SHORT_DEFAULT_CHART_COUNT = 261
