"""assets_module

Revision ID: 186efc806606
Revises: 8741905d94b7
Create Date: 2026-04-19 12:59:07.985405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186efc806606'
down_revision: Union[str, None] = '8741905d94b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('depreciation_method', sa.Enum('STRAIGHT_LINE', 'DECLINING_BALANCE', 'UNITS_OF_PRODUCTION', name='depreciationmethod'), nullable=False),
    sa.Column('useful_life_years', sa.Integer(), nullable=False),
    sa.Column('depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('asset_account_id', sa.String(), nullable=True),
    sa.Column('accumulated_dep_account_id', sa.String(), nullable=True),
    sa.Column('depreciation_expense_account_id', sa.String(), nullable=True),
    sa.Column('gain_on_disposal_account_id', sa.String(), nullable=True),
    sa.Column('loss_on_disposal_account_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_categories_tenant_id'), 'asset_categories', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('asset_number', sa.String(length=50), nullable=False),
    sa.Column('name_ar', sa.String(length=300), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=True),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISPOSED', 'SCRAPPED', 'UNDER_MAINTENANCE', name='assetstatus'), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('useful_life_years', sa.Integer(), nullable=False),
    sa.Column('depreciation_method', sa.Enum('STRAIGHT_LINE', 'DECLINING_BALANCE', 'UNITS_OF_PRODUCTION', name='depreciationmethod'), nullable=False),
    sa.Column('depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('responsible_person', sa.String(length=200), nullable=True),
    sa.Column('cost_center_id', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('warranty_expiry', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('book_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('last_depreciation_date', sa.DateTime(), nullable=True),
    sa.Column('disposal_date', sa.DateTime(), nullable=True),
    sa.Column('disposal_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('disposal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_number'), 'assets', ['asset_number'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('depreciation_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('period_date', sa.DateTime(), nullable=False),
    sa.Column('depreciation_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('book_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('journal_entry_id', sa.String(), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depreciation_lines_asset_id'), 'depreciation_lines', ['asset_id'], unique=False)
    op.create_index(op.f('ix_depreciation_lines_tenant_id'), 'depreciation_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_depreciation_lines_tenant_id'), table_name='depreciation_lines')
    op.drop_index(op.f('ix_depreciation_lines_asset_id'), table_name='depreciation_lines')
    op.drop_table('depreciation_lines')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_number'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_asset_categories_tenant_id'), table_name='asset_categories')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
