"""sales_module

Revision ID: 58445cd9ac61
Revises: 5cccf6d8404d
Create Date: 2026-04-19 13:35:45.202222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58445cd9ac61'
down_revision: Union[str, None] = '5cccf6d8404d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('customer_number', sa.String(length=50), nullable=False),
    sa.Column('customer_type', sa.Enum('INDIVIDUAL', 'COMPANY', 'GOVERNMENT', name='customertype'), nullable=False),
    sa.Column('name_ar', sa.String(length=300), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=True),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('cr_number', sa.String(length=20), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=300), nullable=True),
    sa.Column('address_building', sa.String(length=20), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_district', sa.String(length=100), nullable=True),
    sa.Column('address_postal', sa.String(length=10), nullable=True),
    sa.Column('address_country', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('ar_account_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ar_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='quotationstatus'), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=False)
    op.create_index(op.f('ix_quotations_tenant_id'), 'quotations', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('invoice_type', sa.Enum('STANDARD', 'SIMPLIFIED', name='invoicetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'SENT', 'PAID', 'PARTIAL', 'OVERDUE', 'CANCELLED', 'ZATCA_PENDING', 'ZATCA_CLEARED', 'ZATCA_REJECTED', name='invoicestatus'), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('supply_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('seller_name_ar', sa.String(length=300), nullable=False),
    sa.Column('seller_vat_number', sa.String(length=20), nullable=True),
    sa.Column('seller_cr_number', sa.String(length=20), nullable=True),
    sa.Column('seller_address', sa.Text(), nullable=True),
    sa.Column('buyer_name_ar', sa.String(length=300), nullable=False),
    sa.Column('buyer_vat_number', sa.String(length=20), nullable=True),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('zatca_status', sa.String(length=50), nullable=True),
    sa.Column('zatca_response', sa.Text(), nullable=True),
    sa.Column('zatca_cleared_at', sa.DateTime(), nullable=True),
    sa.Column('quotation_id', sa.String(), nullable=True),
    sa.Column('journal_entry_id', sa.String(), nullable=True),
    sa.Column('fiscal_year_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('quotation_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quotation_id', sa.String(), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.Column('description_ar', sa.String(length=500), nullable=False),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_lines_quotation_id'), 'quotation_lines', ['quotation_id'], unique=False)
    op.create_table('credit_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('credit_note_number', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('original_invoice_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('zatca_status', sa.String(length=50), nullable=True),
    sa.Column('journal_entry_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_credit_notes_credit_note_number'), 'credit_notes', ['credit_note_number'], unique=False)
    op.create_index(op.f('ix_credit_notes_tenant_id'), 'credit_notes', ['tenant_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.Column('description_ar', sa.String(length=500), nullable=False),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_category', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CHEQUE', 'CREDIT_CARD', 'MADA', 'STC_PAY', name='paymentmethod'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('bank_account_id', sa.String(), nullable=True),
    sa.Column('journal_entry_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('credit_note_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('credit_note_id', sa.String(), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.Column('description_ar', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_note_lines_credit_note_id'), 'credit_note_lines', ['credit_note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_note_lines_credit_note_id'), table_name='credit_note_lines')
    op.drop_table('credit_note_lines')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_credit_notes_tenant_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_credit_note_number'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.drop_index(op.f('ix_quotation_lines_quotation_id'), table_name='quotation_lines')
    op.drop_table('quotation_lines')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_quotations_tenant_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_number'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
