"""notifications_module

Revision ID: 5cccf6d8404d
Revises: 186efc806606
Create Date: 2026-04-19 13:13:08.729962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cccf6d8404d'
down_revision: Union[str, None] = '186efc806606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_alert_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('warranty_alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('warranty_alert_days', sa.Integer(), nullable=False),
    sa.Column('full_depreciation_alert', sa.Boolean(), nullable=False),
    sa.Column('depreciation_due_alert', sa.Boolean(), nullable=False),
    sa.Column('depreciation_due_days', sa.Integer(), nullable=False),
    sa.Column('high_depreciation_alert', sa.Boolean(), nullable=False),
    sa.Column('high_depreciation_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('ASSET_WARRANTY_EXPIRY', 'ASSET_FULLY_DEPRECIATED', 'ASSET_DEPRECIATION_DUE', 'ASSET_HIGH_DEPRECIATION', 'GENERAL', name='notificationtype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationseverity'), nullable=False),
    sa.Column('title_ar', sa.String(length=300), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('message_ar', sa.Text(), nullable=False),
    sa.Column('message_en', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('asset_alert_settings')
    # ### end Alembic commands ###
