"""tenant_company_profile

Revision ID: bd48369ac73e
Revises: 5a65f9ec4ecc
Create Date: 2026-04-19 15:12:18.602159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd48369ac73e'
down_revision: Union[str, None] = '5a65f9ec4ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('name_en', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('vat_number', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('cr_number', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('address_street', sa.String(length=300), nullable=True))
    op.add_column('tenants', sa.Column('address_building', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('address_city', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('address_district', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('address_postal', sa.String(length=10), nullable=True))
    op.add_column('tenants', sa.Column('address_country', sa.String(length=3), nullable=True, server_default='SA'))
    op.add_column('tenants', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('logo_data', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('currency', sa.String(length=3), nullable=True, server_default='SAR'))
    op.add_column('tenants', sa.Column('fiscal_year_start', sa.Integer(), nullable=True, server_default='1'))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'fiscal_year_start')
    op.drop_column('tenants', 'currency')
    op.drop_column('tenants', 'logo_data')
    op.drop_column('tenants', 'logo_url')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'address_country')
    op.drop_column('tenants', 'address_postal')
    op.drop_column('tenants', 'address_district')
    op.drop_column('tenants', 'address_city')
    op.drop_column('tenants', 'address_building')
    op.drop_column('tenants', 'address_street')
    op.drop_column('tenants', 'cr_number')
    op.drop_column('tenants', 'vat_number')
    op.drop_column('tenants', 'name_en')
    # ### end Alembic commands ###
