"""customer_extended

Revision ID: efb60162af1b
Revises: bd48369ac73e
Create Date: 2026-04-19 17:06:15.607707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb60162af1b'
down_revision: Union[str, None] = 'bd48369ac73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('owner_name', sa.String(length=200), nullable=True))
    op.add_column('customers', sa.Column('owner_national_id', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('license_number', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('license_expiry', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('activity_type', sa.String(length=200), nullable=True))
    op.add_column('customers', sa.Column('address_additional', sa.String(length=10), nullable=True))
    op.add_column('customers', sa.Column('phone2', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('cr_document', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('vat_document', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('national_id_document', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('license_document', sa.Text(), nullable=True))
    op.alter_column('tenants', 'address_country',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'SA'::character varying"))
    op.alter_column('tenants', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False,
               existing_server_default=sa.text("'SAR'::character varying"))
    op.alter_column('tenants', 'fiscal_year_start',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'fiscal_year_start',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('tenants', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'SAR'::character varying"))
    op.alter_column('tenants', 'address_country',
               existing_type=sa.VARCHAR(length=3),
               nullable=True,
               existing_server_default=sa.text("'SA'::character varying"))
    op.drop_column('customers', 'license_document')
    op.drop_column('customers', 'national_id_document')
    op.drop_column('customers', 'vat_document')
    op.drop_column('customers', 'cr_document')
    op.drop_column('customers', 'phone2')
    op.drop_column('customers', 'address_additional')
    op.drop_column('customers', 'activity_type')
    op.drop_column('customers', 'license_expiry')
    op.drop_column('customers', 'license_number')
    op.drop_column('customers', 'owner_national_id')
    op.drop_column('customers', 'owner_name')
    # ### end Alembic commands ###
