"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ACTIVITIES_LIST, PLANS_LIST, type PlanConfig } from "@/lib/activityConfig";
import { PUBLIC_CONTACT, publicContactLinks } from "@/lib/publicContact";

const Icon = ({ name }: { name: "arrow" | "check" | "chart" | "receipt" | "box" | "users" | "shield" | "mail" | "phone" | "pin" }) => {
  const common = { width: 18, height: 18, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.9, strokeLinecap: "round" as const, strokeLinejoin: "round" as const };
  if (name === "arrow") return <svg {...common}><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>;
  if (name === "check") return <svg {...common}><polyline points="20 6 9 17 4 12"/></svg>;
  if (name === "chart") return <svg {...common}><line x1="4" y1="20" x2="20" y2="20"/><line x1="7" y1="16" x2="7" y2="10"/><line x1="12" y1="16" x2="12" y2="4"/><line x1="17" y1="16" x2="17" y2="7"/></svg>;
  if (name === "receipt") return <svg {...common}><path d="M6 2h12v20l-3-2-3 2-3-2-3 2z"/><line x1="9" y1="7" x2="15" y2="7"/><line x1="9" y1="11" x2="15" y2="11"/></svg>;
  if (name === "box") return <svg {...common}><path d="m21 8-9 5-9-5 9-5z"/><path d="M3 8v9l9 5 9-5V8"/><path d="M12 13v9"/></svg>;
  if (name === "users") return <svg {...common}><circle cx="9" cy="8" r="3"/><path d="M3 21v-2a6 6 0 0 1 12 0v2"/><path d="M16 4a3 3 0 0 1 0 6"/><path d="M21 21v-2a5 5 0 0 0-3-4.58"/></svg>;
  if (name === "shield") return <svg {...common}><path d="M12 22s8-3.7 8-10V5l-8-3-8 3v7c0 6.3 8 10 8 10z"/><path d="m9 12 2 2 4-4"/></svg>;
  if (name === "mail") return <svg {...common}><rect x="3" y="5" width="18" height="14" rx="1"/><polyline points="3 7 12 13 21 7"/></svg>;
  if (name === "phone") return <svg {...common}><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1A19.5 19.5 0 0 1 4.7 13a19.8 19.8 0 0 1-3.1-8.7A2 2 0 0 1 3.6 2h3a2 2 0 0 1 2 1.7c.1 1 .4 1.9.7 2.8a2 2 0 0 1-.4 2.1L7.9 9.9a16 16 0 0 0 6.2 6.2l1.3-1.3a2 2 0 0 1 2.1-.4c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.7 2z"/></svg>;
  return <svg {...common}><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0z"/><circle cx="12" cy="10" r="2.5"/></svg>;
};

const modules = [
  ["chart", "المحاسبة اليومية", "قيود وتقارير وميزان مراجعة منظم"], ["receipt", "المبيعات والفوترة", "فواتير وعروض أسعار ومرتجعات"],
  ["box", "المخزون والمشتريات", "أصناف ومستودعات وسيريالات"], ["users", "إدارة الفريق", "صلاحيات ومستخدمون ومندوبون"],
] as const;

export default function LandingPage() {
  const { locale = "ar" } = useParams<{ locale: string }>();
  const ar = locale === "ar";
  const [plans, setPlans] = useState<PlanConfig[]>(PLANS_LIST);
  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8001/api/v1"}/admin/plans-config/public`)
      .then((r) => r.ok ? r.json() : null)
      .then((data) => { if (data?.plans && Object.keys(data.plans).length) setPlans(Object.values(data.plans) as PlanConfig[]); })
      .catch(() => {});
  }, []);
  const visiblePlans = plans.filter((plan) => (plan as PlanConfig & { is_active?: boolean }).is_active !== false);
  return <main className="public-site landing-palette-preview" dir={ar ? "rtl" : "ltr"}>
    <style>{`
      .public-site{--ink:#173a2f;--green:#3E0865;--green2:#75617F;--paper:#fffefa;--line:#c8d0c7;min-height:100vh;background:var(--paper);color:var(--ink);font-family:var(--font-cairo),Cairo,Arial,sans-serif}
      .public-site *{box-sizing:border-box}.public-site a{text-decoration:none;color:inherit}.marketing-wrap{width:min(1180px,92vw);margin:auto}.public-header{height:76px;background:#fff;border-bottom:1px solid #dce3da;position:sticky;top:0;z-index:30}.public-header .marketing-wrap{height:100%;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand-logo{display:block;width:192px;height:auto;object-fit:contain}.public-nav{display:flex;align-items:center;gap:22px;font-size:13px;font-weight:700;color:#5f7068}.public-nav a:hover{color:var(--green)}.header-actions{display:flex;align-items:center;gap:8px}.public-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:40px;padding:0 15px;border:1px solid var(--green);font:800 13px inherit;cursor:pointer;transition:.16s ease}.public-btn.primary{color:#fff;background:linear-gradient(180deg,#17735c,#3E0865);box-shadow:0 3px 0 #084535}.public-btn.secondary{background:#fff;color:var(--green)}
      .hero{position:relative;overflow:hidden;padding:80px 0 68px;background:radial-gradient(circle at 16% 20%,#e1f0e5 0,transparent 31%),linear-gradient(180deg,#fbfdf8,#eef5ef)}.hero-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:55px;align-items:center}.eyebrow{display:inline-flex;align-items:center;gap:7px;padding:5px 10px;border:1px solid #b9cfbd;background:#f9fdf8;color:#75617F;font-size:11px;font-weight:800}.hero h1{font-size:clamp(32px,4vw,54px);line-height:1.2;margin:18px 0 16px;letter-spacing:-1px}.hero h1 strong{color:var(--green)}.hero p{max-width:580px;margin:0 0 24px;font-size:16px;line-height:2;color:#5a6b62}.hero-actions{display:flex;flex-wrap:wrap;gap:10px}.hero-note{display:flex;align-items:center;gap:8px;margin-top:20px;color:#597165;font-size:12px}.hero-note i{color:#e0a80e}.product-frame{border:1px solid #bdccbf;background:#fffefa;box-shadow:13px 15px 0 rgba(62,8,101,.13);padding:10px}.window-bar{height:32px;display:flex;align-items:center;gap:5px;padding:0 10px;background:linear-gradient(#f5f8f3,#e2e9e1);border:1px solid var(--line);font:800 10px monospace;color:#527060}.dots{display:flex;gap:4px;margin-inline-end:auto}.dots i{width:7px;height:7px;border-radius:50%;background:#a9b9ac}.ledger-top{display:grid;grid-template-columns:140px 1fr;gap:8px;margin-top:8px}.ledger-side{min-height:244px;padding:12px 9px;background:#3E0865;color:#e8f3e9}.ledger-side b{display:block;margin:0 0 13px;font-size:11px}.ledger-side span{display:block;padding:7px 4px;border-bottom:1px solid rgba(255,255,255,.14);font-size:9px}.ledger-work{border:1px solid var(--line);padding:10px}.ledger-work-head{display:flex;justify-content:space-between;align-items:center;font-weight:800;font-size:11px}.ledger-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:10px 0}.ledger-kpi{padding:8px;border:1px solid #d7e0d6;background:#f6faf5}.ledger-kpi small{display:block;color:#76857a;font-size:8px}.ledger-kpi b{font:800 13px monospace;color:#3E0865}.ledger-table{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr;border-top:1px solid var(--line);border-left:1px solid var(--line)}.ledger-table span{min-height:27px;padding:7px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);font-size:8px}.ledger-table span:nth-child(-n+4){font-weight:800;background:#F4EFF7}.ledger-table span:nth-child(8n+5),.ledger-table span:nth-child(8n+6),.ledger-table span:nth-child(8n+7),.ledger-table span:nth-child(8n+8){background:#fbfdf9}
      .proof{border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:#fff;padding:19px 0}.proof-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:0}.proof-item{padding:0 21px;border-inline-start:1px solid #d9e1d8;text-align:center}.proof-item:first-child{border:0}.proof-item b{display:block;font:800 20px monospace;color:var(--green)}.proof-item span{font-size:11px;color:#718078}.section{padding:76px 0}.section.paper{background:#fff}.section-heading{max-width:640px;margin:0 auto 32px;text-align:center}.section-heading span{color:#75617F;font-size:11px;font-weight:900;letter-spacing:.4px}.section-heading h2{margin:8px 0 10px;font-size:clamp(25px,3vw,38px)}.section-heading p{margin:0;color:#66776e;line-height:1.8;font-size:14px}.module-grid{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line);background:#fff}.module-card{padding:22px;border-inline-start:1px solid var(--line);min-height:180px}.module-card:first-child{border:0}.module-icon{width:40px;height:40px;display:grid;place-items:center;background:#F4EFF7;color:var(--green);border:1px solid #bdd1c0}.module-card h3{margin:16px 0 7px;font-size:15px}.module-card p{margin:0;color:#6b7b72;font-size:12px;line-height:1.8}.activity-strip{display:grid;grid-template-columns:1.1fr 1fr;gap:40px;align-items:center;padding:34px;border:1px solid #b9cbbb;background:#F4EFF7}.activity-copy h2{font-size:28px;margin:0 0 10px}.activity-copy p{color:#586c60;line-height:1.9;font-size:14px}.activity-list{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.activity-list span{padding:9px 11px;border:1px solid #c1d1c1;background:#fffefa;font-size:11px;font-weight:700}.plans{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.plan{position:relative;border:1px solid var(--line);background:#fffefa;padding:21px}.plan.popular{border:2px solid var(--green);box-shadow:5px 6px 0 #d7e5d8}.plan .tag{position:absolute;top:-12px;inset-inline-start:17px;padding:4px 9px;background:var(--green);color:#fff;font-size:10px;font-weight:800}.plan h3{margin:0;font-size:19px}.plan .price{margin:12px 0;font:800 26px monospace;color:var(--green)}.plan .price small{font:700 10px Cairo,sans-serif;color:#6c7a71}.plan ul{margin:0 0 17px;padding:0;list-style:none}.plan li{display:flex;gap:7px;margin:8px 0;color:#607167;font-size:11px}.plan li svg{color:#75617F;flex:0 0 auto;width:14px}.footer{padding:42px 0 22px;background:#123c31;color:#e6f0e8}.footer-grid{display:grid;grid-template-columns:1.3fr repeat(3,1fr);gap:32px}.footer .brand-logo{width:180px;filter:brightness(0) invert(1);margin-bottom:14px}.footer p,.footer a{color:#c6d7ca;font-size:12px;line-height:1.9}.footer h4{font-size:13px;margin:0 0 11px;color:#fff}.footer a{display:block;margin:4px 0}.contact-line{display:flex!important;align-items:center;gap:8px}.footer-bottom{margin-top:30px;padding-top:16px;border-top:1px solid rgba(255,255,255,.16);font-size:10px;color:#b8cbbd}
      @media(max-width:820px){.public-nav{display:none}.hero{padding:45px 0}.hero-grid,.activity-strip{grid-template-columns:1fr;gap:25px}.product-frame{max-width:570px;margin:auto}.module-grid{grid-template-columns:repeat(2,1fr)}.module-card:nth-child(3){border-inline-start:0;border-top:1px solid var(--line)}.module-card:nth-child(4){border-top:1px solid var(--line)}.plans{grid-template-columns:1fr}.footer-grid{grid-template-columns:1fr 1fr}.proof-grid{grid-template-columns:repeat(2,1fr);gap:18px}.proof-item:nth-child(3){border:0}.header-actions .secondary{display:none}}@media(max-width:480px){.public-header{height:64px}.brand-logo{width:143px}.header-actions .primary{min-height:34px;padding:0 9px;font-size:11px}.hero h1{font-size:32px}.hero p{font-size:14px}.hero-actions{display:grid;grid-template-columns:1fr}.hero-actions .public-btn{width:100%}.ledger-top{grid-template-columns:95px 1fr}.ledger-side{min-height:220px}.ledger-kpis{grid-template-columns:1fr}.ledger-kpi:nth-child(n+2){display:none}.proof-item{padding:0 9px}.module-grid{grid-template-columns:1fr}.module-card{border:0!important;border-top:1px solid var(--line)!important;min-height:auto}.module-card:first-child{border-top:0!important}.footer-grid{grid-template-columns:1fr}.activity-list{grid-template-columns:1fr}.section{padding:52px 0}}

      /* تجربة ألوان صفحة الهبوط فقط: أزرق ضبابي هادئ + حياد دافئ. */
      .landing-palette-preview{--ink:#2B1A32;--green:#3E0865;--green2:#5A187E;--paper:#FAF9F7;--line:#E4D9EA;background:var(--paper);color:var(--ink)}
      .landing-palette-preview .public-header{background:#FFFDFF;border-color:#E0E6EB}.landing-palette-preview .public-nav{color:#657384}.landing-palette-preview .public-nav a:hover{color:var(--green)}
      .landing-palette-preview .public-btn{border-color:var(--green)}.landing-palette-preview .public-btn.primary{background:linear-gradient(180deg,#75617F,#3E0865);box-shadow:0 3px 0 #26033F}.landing-palette-preview .public-btn.secondary{background:#FFFDFF;color:var(--green)}
      .landing-palette-preview .hero{background:radial-gradient(circle at 16% 20%,#E6EDF4 0,transparent 31%),linear-gradient(180deg,#FFFDFF,#F1F5F8)}.landing-palette-preview .eyebrow{border-color:#C8D6E4;background:#F5F8FB;color:#4C126D}.landing-palette-preview .hero h1 strong{color:var(--green)}.landing-palette-preview .hero p{color:#5C6B7B}.landing-palette-preview .hero-note{color:#657688}.landing-palette-preview .hero-note i{color:#D39361}
      .landing-palette-preview .product-frame{border-color:#C9D7E4;background:#FFFDFF;box-shadow:13px 15px 0 rgba(66,94,122,.13)}.landing-palette-preview .window-bar{background:linear-gradient(#F6F8FA,#E7EDF3);color:#5D7185}.landing-palette-preview .dots i{background:#AABACA}.landing-palette-preview .ledger-side{background:#3E0865;color:#EDF4FA}.landing-palette-preview .ledger-kpi{border-color:#D5E0E9;background:#F3F7FA}.landing-palette-preview .ledger-kpi small{color:#748394}.landing-palette-preview .ledger-kpi b{color:#3E0865}.landing-palette-preview .ledger-table span:nth-child(-n+4){background:#E8EFF5}.landing-palette-preview .ledger-table span:nth-child(8n+5),.landing-palette-preview .ledger-table span:nth-child(8n+6),.landing-palette-preview .ledger-table span:nth-child(8n+7),.landing-palette-preview .ledger-table span:nth-child(8n+8){background:#FBFCFD}
      .landing-palette-preview .proof-item{border-color:#E1E7EC}.landing-palette-preview .proof-item b{color:var(--green)}.landing-palette-preview .proof-item span{color:#738191}.landing-palette-preview .section-heading span{color:#4C126D}.landing-palette-preview .section-heading p{color:#75617F}.landing-palette-preview .module-icon{border-color:#C9D9E7;background:#F4EFF7;color:var(--green)}.landing-palette-preview .module-card p{color:#687788}
      .landing-palette-preview .activity-strip{border-color:#C5D5E3;background:#F4EFF7}.landing-palette-preview .activity-copy p{color:#5A6D80}.landing-palette-preview .activity-list span{border-color:#D1DEE8;background:#FFFDFF}.landing-palette-preview .plan{background:#FFFDFF}.landing-palette-preview .plan.popular{border-color:var(--green);box-shadow:5px 6px 0 #D9E5EF}.landing-palette-preview .plan .tag{background:var(--green)}.landing-palette-preview .plan .price{color:var(--green)}.landing-palette-preview .plan .price small{color:#6B7A8A}.landing-palette-preview .plan li{color:#637283}.landing-palette-preview .plan li svg{color:#4C126D}
      .landing-palette-preview .footer{background:#2B1A32;color:#F4EFF7}.landing-palette-preview .footer p,.landing-palette-preview .footer a{color:#CED9E4}.landing-palette-preview .footer-bottom{color:#BAC9D7}
    `}</style>
    <header className="public-header"><div className="marketing-wrap"><Link href={`/${locale}/landing`}><img className="brand-logo" src="/logo-masar-blue.png" alt="MASAR - مسار للحلول المحاسبية"/></Link><nav className="public-nav"><Link href="#features">{ar ? "المزايا" : "Features"}</Link><Link href="#plans">{ar ? "الباقات" : "Plans"}</Link><Link href={`/${locale}/landing/contact`}>{ar ? "تواصل معنا" : "Contact"}</Link></nav><div className="header-actions"><Link className="public-btn secondary" href={`/${locale}/login`}>{ar ? "دخول" : "Sign in"}</Link><Link className="public-btn primary" href={`/${locale}/register`}>{ar ? "ابدأ الآن" : "Start now"}</Link></div></div></header>
    <section className="hero"><div className="marketing-wrap hero-grid"><div><div className="eyebrow"><Icon name="shield"/>{ar ? "منصة محاسبية منظمة للشركات السعودية" : "An organized accounting platform for Saudi businesses"}</div><h1>{ar ? <>أدر أعمال شركتك من <strong>دفتر واحد واضح.</strong></> : <>Run your company from <strong>one clear ledger.</strong></>}</h1><p>{ar ? "مَسار يجمع المحاسبة والمبيعات والمخزون والمشتريات في نظام عملي مرتب، لتتابع الأرقام والعمليات بثقة." : "MASAR brings accounting, sales, inventory and purchasing into one orderly workspace."}</p><div className="hero-actions"><Link className="public-btn primary" href={`/${locale}/register`}>{ar ? "أنشئ مساحة شركتك" : "Create your workspace"}<Icon name="arrow"/></Link><Link className="public-btn secondary" href={`/${locale}/login`}>{ar ? "تسجيل الدخول" : "Sign in"}</Link></div><div className="hero-note"><i>★★★★★</i>{ar ? "تصميم عملي مناسب للعمل اليومي، وليس لوحة مزدحمة." : "A practical workspace for daily operations."}</div></div><div className="product-frame" aria-label={ar ? "معاينة النظام" : "System preview"}><div className="window-bar"><span>{ar ? "مَسار ERP · لوحة العمليات" : "MASAR ERP · Operations"}</span><div className="dots"><i/><i/><i/></div></div><div className="ledger-top"><aside className="ledger-side"><b>MASAR ERP</b><span>{ar ? "لوحة العمليات" : "Operations"}</span><span>{ar ? "المبيعات" : "Sales"}</span><span>{ar ? "المشتريات" : "Purchases"}</span><span>{ar ? "المخزون" : "Inventory"}</span><span>{ar ? "التقارير" : "Reports"}</span></aside><div className="ledger-work"><div className="ledger-work-head"><span>{ar ? "ملخص اليوم" : "Today summary"}</span><span>{ar ? "24 أغسطس" : "24 Aug"}</span></div><div className="ledger-kpis"><div className="ledger-kpi"><small>{ar ? "المبيعات" : "Sales"}</small><b>18,450</b></div><div className="ledger-kpi"><small>{ar ? "المقبوضات" : "Collected"}</small><b>12,700</b></div><div className="ledger-kpi"><small>{ar ? "فواتير" : "Invoices"}</small><b>24</b></div></div><div className="ledger-table"><span>{ar ? "المستند" : "Document"}</span><span>{ar ? "العميل" : "Customer"}</span><span>{ar ? "القيمة" : "Amount"}</span><span>{ar ? "الحالة" : "Status"}</span><span>INV-0241</span><span>{ar ? "شركة المثال" : "Example Co."}</span><span>4,250</span><span>{ar ? "مكتمل" : "Done"}</span><span>INV-0242</span><span>{ar ? "متجر المدينة" : "City Store"}</span><span>2,800</span><span>{ar ? "معلق" : "Pending"}</span></div></div></div></div></div></section>
    <section className="proof"><div className="marketing-wrap proof-grid"><div className="proof-item"><b>01</b><span>{ar ? "مساحة عمل واحدة" : "One workspace"}</span></div><div className="proof-item"><b>08+</b><span>{ar ? "وحدات تشغيل مترابطة" : "Connected modules"}</span></div><div className="proof-item"><b>RTL</b><span>{ar ? "واجهة عربية أصلية" : "Arabic-first interface"}</span></div><div className="proof-item"><b>24/7</b><span>{ar ? "وصول من أي مكان" : "Access anywhere"}</span></div></div></section>
    <section className="section paper" id="features"><div className="marketing-wrap"><div className="section-heading"><span>{ar ? "مبني للعمل اليومي" : "Built for daily work"}</span><h2>{ar ? "كل وحدة في مكانها الصحيح." : "Every workflow in its proper place."}</h2><p>{ar ? "واجهة عملية متماسكة تساعدك على تنفيذ العمليات ومراجعتها بدل التنقل بين صفحات كثيرة." : "A coherent workspace for executing and reviewing operations without needless switching."}</p></div><div className="module-grid">{modules.map(([icon,title,text])=><article className="module-card" key={title}><div className="module-icon"><Icon name={icon}/></div><h3>{ar ? title : title}</h3><p>{ar ? text : text}</p></article>)}</div></div></section>
    <section className="section"><div className="marketing-wrap activity-strip"><div className="activity-copy"><span className="eyebrow">{ar ? "تهيئة مرنة" : "Flexible setup"}</span><h2>{ar ? "ابدأ وفق نشاطك، ثم توسع بهدوء." : "Start for your business, then grow with confidence."}</h2><p>{ar ? "من الجوالات وقطع الغيار إلى الصيدليات والبقالات، نرتب نقطة البداية بما يناسب طبيعة عملياتك." : "From mobile retail to pharmacies and groceries, start with the workflows that fit you."}</p><Link className="public-btn secondary" href={`/${locale}/register`}>{ar ? "ابدأ الإعداد" : "Start setup"}<Icon name="arrow"/></Link></div><div className="activity-list">{ACTIVITIES_LIST.slice(0,6).map((activity)=><span key={activity.key}>{ar ? activity.label_ar : activity.label_en}</span>)}</div></div></section>
    <section className="section paper" id="plans"><div className="marketing-wrap"><div className="section-heading"><span>{ar ? "باقات واضحة" : "Clear plans"}</span><h2>{ar ? "اختر نقطة البداية المناسبة." : "Choose the right starting point."}</h2><p>{ar ? "ابدأ بالتجربة، ثم انتقل إلى الباقة المناسبة عبر إدارة الاشتراك في النظام." : "Begin with a trial, then move to the appropriate plan through subscription management."}</p></div><div className="plans">{visiblePlans.map((plan, index)=><article className={`plan ${plan.popular || index === 1 ? "popular" : ""}`} key={plan.key}>{(plan.popular || index === 1)&&<span className="tag">{ar ? "الأكثر اختيارًا" : "Popular"}</span>}<h3>{ar ? plan.label_ar : plan.label_en}</h3><div className="price">{plan.price_monthly === 0 ? (ar ? "مجانًا" : "Free") : `${plan.price_monthly}`} {plan.price_monthly > 0 && <small>{ar ? "ر.س / شهر" : "SAR / mo"}</small>}</div><ul>{(ar ? plan.features_ar : plan.features_en).slice(0,4).map((feature)=><li key={feature}><Icon name="check"/>{feature}</li>)}</ul><Link className="public-btn secondary" href={`/${locale}/register?plan=${plan.key}`}>{ar ? "ابدأ بهذه الباقة" : "Choose this plan"}</Link></article>)}</div></div></section>
    <footer className="footer"><div className="marketing-wrap"><div className="footer-grid"><div><img className="brand-logo" src="/logo-masar-blue.png" alt="MASAR"/><p>{ar ? "حلول محاسبية عملية تساعد الشركات على تنظيم أعمالها ومتابعة عملياتها من منصة واحدة." : "Practical accounting solutions for organized company operations."}</p></div><div><h4>{ar ? "المنصة" : "Platform"}</h4><Link href="#features">{ar ? "المزايا" : "Features"}</Link><Link href="#plans">{ar ? "الباقات" : "Plans"}</Link><Link href={`/${locale}/login`}>{ar ? "تسجيل الدخول" : "Sign in"}</Link></div><div><h4>{ar ? "الدعم" : "Support"}</h4><Link href={`/${locale}/landing/contact`}>{ar ? "تواصل معنا" : "Contact us"}</Link><a href={publicContactLinks.whatsapp} target="_blank" rel="noreferrer">{ar ? "واتساب الدعم" : "WhatsApp support"}</a><a href={publicContactLinks.email}>{ar ? "راسلنا بالبريد" : "Email us"}</a></div><div><h4>{ar ? "بيانات التواصل" : "Contact details"}</h4><a className="contact-line" href={publicContactLinks.email}><Icon name="mail"/>{PUBLIC_CONTACT.email}</a><a className="contact-line" href={publicContactLinks.phone}><Icon name="phone"/><span dir="ltr">{PUBLIC_CONTACT.phone}</span></a><span className="contact-line"><Icon name="pin"/>{ar ? PUBLIC_CONTACT.addressAr : PUBLIC_CONTACT.addressEn}</span></div></div><div className="footer-bottom">© {new Date().getFullYear()} MASAR. {ar ? "جميع الحقوق محفوظة." : "All rights reserved."}</div></div></footer>
  </main>;
}
