"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { jwtDecode } from "jwt-decode";
import api from "@/lib/api";
import { useAuthStore } from "@/store/authStore";

export default function LoginPage() {
  const { locale = "ar" } = useParams<{ locale: string }>();
  const ar = locale === "ar";
  const router = useRouter();
  const setAuth = useAuthStore((state) => state.setAuth);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const { data } = await api.post("/auth/login", { email, password }); const token: any = jwtDecode(data.access_token); setAuth(data.access_token, { id: token.sub, tenantId: token.tenant_id, role: token.role }); router.push(token.role === "super_admin" ? `/${locale}/super-admin/dashboard` : `/${locale}/dashboard`); } catch { setError(ar ? "تعذر تسجيل الدخول. راجع البريد وكلمة المرور." : "Unable to sign in. Check your email and password."); } finally { setLoading(false); } };
  return <main className="auth-public" dir={ar ? "rtl" : "ltr"}><style>{`
    .auth-public{min-height:100vh;background:linear-gradient(135deg,#FAF8FB,#FFFDFF 56%,#F4EFF7);color:#2B1A32;font-family:var(--font-cairo),Cairo,Arial,sans-serif}.auth-header{height:76px;display:flex;align-items:center;justify-content:center;padding:0 5%;border-bottom:1px solid #E4D9EA;background:#fff}.auth-header img{width:182px;height:auto;object-fit:contain}.auth-shell{width:min(1120px,92vw);margin:0 auto;min-height:calc(100vh - 76px);display:grid;grid-template-columns:.9fr 1.1fr;align-items:center;gap:70px;padding:42px 0}.auth-copy{padding:16px}.auth-kicker{display:inline-block;padding:5px 9px;border:1px solid #D6C9DD;color:#75617F;background:#F8F9FA;font-size:10px;font-weight:900}.auth-copy h1{max-width:440px;margin:17px 0 12px;font-size:clamp(30px,4vw,46px);line-height:1.25}.auth-copy p{max-width:430px;margin:0;color:#75617F;font-size:14px;line-height:2}.auth-points{display:grid;gap:9px;margin:25px 0 0}.auth-points span{display:flex;align-items:center;gap:8px;font-size:12px;font-weight:700}.auth-points i{display:grid;place-items:center;width:20px;height:20px;background:#F4EFF7;color:#3E0865;border:1px solid #D7CBDD;font-style:normal}.auth-card{width:min(460px,100%);justify-self:end;border:1px solid #E4D9EA;background:#FFFDFF;box-shadow:8px 9px 0 rgba(54,65,82,.13);padding:0 30px 28px}.auth-card-top{margin:0 -30px 24px;padding:16px 30px;border-bottom:1px solid #E4D9EA;background:#fff}.auth-card-top small{color:#75617F;font-size:10px;font-weight:800}.auth-card h2{margin:0 0 6px;font-size:28px}.auth-card .lead{margin:0 0 23px;color:#748279;font-size:12px}.auth-field{display:grid;gap:6px;margin-bottom:15px}.auth-field label{font-size:11px;font-weight:900}.auth-field input{height:45px;padding:0 12px;border:1px solid #c8d0c7;background:#fff;font:13px inherit;outline:none}.auth-field input:focus{border-color:#3E0865;box-shadow:0 0 0 3px #F4EFF7}.auth-submit{width:100%;height:45px;margin-top:5px;border:1px solid #3E0865;background:#3E0865;box-shadow:0 3px 0 #26033F;color:#fff;font:800 13px inherit;cursor:pointer}.auth-error{margin-bottom:14px;padding:9px 10px;border:1px solid #e2b7ac;background:#fff2ef;color:#9b4230;font-size:11px}.auth-links{display:flex;justify-content:space-between;gap:10px;margin-top:19px;padding-top:15px;border-top:1px solid #E4D9EA;color:#75617F;font-size:11px}.auth-links a{font-weight:900;color:#3E0865;text-decoration:none}.auth-foot{margin-top:17px;color:#718077;text-align:center;font-size:10px}.auth-foot a{color:#3E0865;font-weight:800;text-decoration:none}@media(max-width:760px){.auth-header{height:70px}.auth-header img{width:155px}.auth-shell{min-height:calc(100vh - 70px);grid-template-columns:1fr;padding:24px 0 35px}.auth-copy{display:none}.auth-card{justify-self:center;box-shadow:4px 5px 0 rgba(54,65,82,.11);padding:0 21px 23px}.auth-card-top{margin:0 -21px 22px;padding:13px 21px}.auth-card h2{font-size:26px}.auth-links{flex-wrap:wrap}.auth-submit{height:47px}}`}</style>
    <header className="auth-header"><Link href={`/${locale}/landing`}><img src="/logo-masar-blue.png" alt="MASAR - مسار للحلول المحاسبية"/></Link></header>
    <div className="auth-shell"><section className="auth-copy"><span className="auth-kicker">{ar ? "مساحة عمل محاسبية منظمة" : "An organized accounting workspace"}</span><h1>{ar ? "تابع أعمال شركتك من مكان واحد واضح." : "Follow your company operations from one clear place."}</h1><p>{ar ? "ادخل إلى مساحة شركتك لمراجعة العمليات والفواتير والمخزون والتقارير ضمن واجهة عملية متناسقة." : "Sign in to review operations, invoices, inventory and reports in one practical workspace."}</p><div className="auth-points"><span><i>✓</i>{ar ? "دخول آمن بحسب صلاحية المستخدم" : "Secure access based on user role"}</span><span><i>✓</i>{ar ? "واجهة عربية متجاوبة للاستخدام اليومي" : "Arabic-first responsive workspace"}</span><span><i>✓</i>{ar ? "تقارير وعمليات في سجل واحد منظم" : "Reports and operations in one organized ledger"}</span></div></section>
      <section className="auth-card"><div className="auth-card-top"><small>{ar ? "دخول آمن إلى مَسار" : "SECURE MASAR ACCESS"}</small></div><h2>{ar ? "تسجيل الدخول" : "Sign in"}</h2><p className="lead">{ar ? "أدخل بيانات حسابك للمتابعة إلى مساحة شركتك." : "Enter your account details to continue to your workspace."}</p>{error && <div className="auth-error">{error}</div>}<form onSubmit={submit}><div className="auth-field"><label htmlFor="email">{ar ? "البريد الإلكتروني" : "Email address"}</label><input id="email" type="email" autoComplete="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="name@company.com" required/></div><div className="auth-field"><label htmlFor="password">{ar ? "كلمة المرور" : "Password"}</label><input id="password" type="password" autoComplete="current-password" value={password} onChange={(event)=>setPassword(event.target.value)} placeholder="••••••••" required/></div><button className="auth-submit" disabled={loading}>{loading ? (ar ? "جارٍ التحقق…" : "Signing in…") : (ar ? "دخول إلى النظام ←" : "Sign in →")}</button></form><div className="auth-links"><span>{ar ? "ليس لديك حساب؟" : "No account yet?"} <Link href={`/${locale}/register`}>{ar ? "إنشاء حساب" : "Create account"}</Link></span><Link href={`/${locale}/landing/contact`}>{ar ? "تحتاج مساعدة؟" : "Need help?"}</Link></div><p className="auth-foot">{ar ? "بالدخول أنت توافق على" : "By signing in you agree to"} <Link href={`/${locale}/landing/terms`}>{ar ? "شروط الاستخدام" : "Terms"}</Link></p></section></div>
  </main>;
}
